package aspire;

import java.util.Map;

final class AppHost {

    void main() throws Exception {
        var builder = DistributedApplication.CreateBuilder();
        var container = builder.addContainer("mycontainer", "nginx");
        var dockerContainer = builder.addDockerfile("dockerapp", "./app");
        var exe = builder.addExecutable("myexe", "echo", ".", new String[] { "hello" });
        var project = builder.addProject("myproject", "./src/MyProject", "https");
        var csharpApp = builder.addCSharpApp("csharpapp", "./src/CSharpApp");
        var cache = builder.addRedis("cache");
        var tool = builder.addDotnetTool("mytool", "dotnet-ef");
        var configParam = builder.addParameterFromConfiguration("myconfig", "MyConfig:Key");
        var secretParam = builder.addParameterFromConfiguration("mysecret", "MyConfig:Secret", true);
        container.withDockerfileBaseImage(new WithDockerfileBaseImageOptions().buildImage("mcr.microsoft.com/dotnet/sdk:8.0"));
        container.withContainerRegistry(new IResource(container.getHandle(), container.getClient()));
        dockerContainer.withHttpEndpoint(new WithHttpEndpointOptions().name("http").targetPort(80.0));
        var endpoint = dockerContainer.getEndpoint("http");
        var expr = ReferenceExpression.refExpr("Host=%s", endpoint);
        var builtConnectionString = builder.addConnectionStringBuilder("customcs", (connectionStringBuilder) -> { var _isEmpty = connectionStringBuilder.isEmpty(); connectionStringBuilder.appendLiteral("Host="); connectionStringBuilder.appendValueProvider(endpoint); connectionStringBuilder.appendLiteral(";Key="); connectionStringBuilder.appendValueProvider(secretParam); var _builtExpression = connectionStringBuilder.build(); });
        builtConnectionString.withConnectionProperty("Host", expr);
        builtConnectionString.withConnectionPropertyValue("Mode", "Development");
        container.withEnvironmentEndpoint("MY_ENDPOINT", endpoint);
        container.withEnvironmentParameter("MY_PARAM", configParam);
        container.withEnvironmentConnectionString("MY_CONN", new IResourceWithConnectionString(builtConnectionString.getHandle(), builtConnectionString.getClient()));
        builtConnectionString.withConnectionProperty("Endpoint", expr);
        builtConnectionString.withConnectionPropertyValue("Protocol", "https");
        container.excludeFromManifest();
        container.excludeFromMcp();
        container.waitForCompletion(new IResource(exe.getHandle(), exe.getClient()));
        container.withDeveloperCertificateTrust(true);
        container.withCertificateTrustScope(CertificateTrustScope.SYSTEM);
        container.withHttpsDeveloperCertificate();
        container.withoutHttpsCertificate();
        container.withChildRelationship(new IResource(exe.getHandle(), exe.getClient()));
        container.withIconName("Database", IconVariant.FILLED);
        container.withHttpProbe(ProbeType.LIVENESS, new WithHttpProbeOptions().path("/health"));
        container.withRemoteImageName("myregistry.azurecr.io/myapp");
        container.withRemoteImageTag("latest");
        container.withMcpServer(new WithMcpServerOptions().path("/mcp"));
        container.withRequiredCommand("docker");
        tool.withToolIgnoreExistingFeeds();
        tool.withToolIgnoreFailedSources();
        tool.withToolPackage("dotnet-ef");
        tool.withToolPrerelease();
        tool.withToolSource("https://api.nuget.org/v3/index.json");
        tool.withToolVersion("8.0.0");
        tool.publishAsDockerFile();
        container.withPipelineStepFactory("custom-build-step", (stepContext) -> { var pipelineContext = stepContext.pipelineContext(); var pipelineModel = pipelineContext.model(); var _pipelineResources = pipelineModel.getResources(); var _pipelineContainer = pipelineModel.findResourceByName("mycontainer"); var pipelineServices = pipelineContext.services(); var pipelineLoggerFactory = pipelineServices.getLoggerFactory(); var pipelineFactoryLogger = pipelineLoggerFactory.createLogger("ValidationAppHost.PipelineContext"); pipelineFactoryLogger.logInformation("Pipeline factory context logger"); var pipelineLogger = pipelineContext.logger(); pipelineLogger.logDebug("Pipeline context logger"); var pipelineSummary = pipelineContext.summary(); pipelineSummary.add("PipelineContext", "Validated"); pipelineSummary.addMarkdown("PipelineMarkdown", "**Validated**"); var executionContext = stepContext.executionContext(); var _isPublishMode = executionContext.isPublishMode(); var stepServices = stepContext.services(); var stepLogger = stepContext.logger(); stepLogger.logInformation("Pipeline step context logger"); var stepSummary = stepContext.summary(); stepSummary.add("PipelineStepContext", "Validated"); var reportingStep = stepContext.reportingStep(); reportingStep.logStep("information", "Reporting step log"); reportingStep.logStepMarkdown("information", "**Reporting step markdown log**"); var reportingTask = reportingStep.createTask("Task created"); reportingTask.updateTask("Task updated"); reportingTask.updateTaskMarkdown("**Task markdown updated**"); reportingTask.completeTask(new CompleteTaskOptions().completionMessage("Task complete")); var markdownTask = reportingStep.createMarkdownTask("**Markdown task created**"); markdownTask.completeTaskMarkdown("**Markdown task complete**", new CompleteTaskMarkdownOptions().completionState("completed-with-warning")); reportingStep.completeStep("Reporting step complete"); reportingStep.completeStepMarkdown("**Reporting step markdown complete**", new CompleteStepMarkdownOptions().completionState("completed-with-warning")); var stepModel = stepContext.model(); var _stepResources = stepModel.getResources(); var _stepContainer = stepModel.findResourceByName("mycontainer"); var stepLoggerFactory = stepServices.getLoggerFactory(); var stepFactoryLogger = stepLoggerFactory.createLogger("ValidationAppHost.PipelineStepContext"); stepFactoryLogger.logDebug("Pipeline step factory logger"); var cancellationToken = stepContext.cancellationToken(); var cacheUriExpression = cache.uriExpression(); var _cacheUri = cacheUriExpression.getValue(cancellationToken); }, new WithPipelineStepFactoryOptions().dependsOn(new String[] { "build" }).requiredBy(new String[] { "deploy" }).tags(new String[] { "custom-build" }).description("Custom pipeline step"));
        container.withPipelineConfiguration((configContext) -> { var configServices = configContext.services(); var configModel = configContext.model(); var _configResources = configModel.getResources(); var _configContainer = configModel.findResourceByName("mycontainer"); var configLoggerFactory = configServices.getLoggerFactory(); var configLogger = configLoggerFactory.createLogger("ValidationAppHost.PipelineConfigurationContext"); configLogger.logInformation("Pipeline configuration logger"); var allSteps = configContext.steps(); var taggedSteps = configContext.getStepsByTag("custom-build"); var _stepName = allSteps[0].name(); var _description = allSteps[0].description(); var _tags = allSteps[0].tags(); var _dependsOnSteps = allSteps[0].dependsOnSteps(); var _requiredBySteps = taggedSteps[0].requiredBySteps(); taggedSteps[0].requiredBy("publish"); allSteps[0].dependsOn("build"); });
        container.withPipelineConfigurationAsync((configContext) -> { var _configServices = configContext.services(); var _configModel = configContext.model(); var _resourceSteps = configContext.steps(); var _taggedSteps = configContext.getStepsByTag("custom-build"); });
        var _appHostDirectory = builder.appHostDirectory();
        var hostEnvironment = builder.environment();
        var _isDevelopment = hostEnvironment.isDevelopment();
        var _isProduction = hostEnvironment.isProduction();
        var _isStaging = hostEnvironment.isStaging();
        var _isSpecificEnvironment = hostEnvironment.isEnvironment("Development");
        var builderConfiguration = builder.getConfiguration();
        var _configValue = builderConfiguration.getConfigValue("MyConfig:Key");
        var _connectionString = builderConfiguration.getConnectionString("customcs");
        var _configSection = builderConfiguration.getSection("MyConfig");
        var _configChildren = builderConfiguration.getChildren();
        var _configExists = builderConfiguration.exists("MyConfig:Key");
        var builderExecutionContext = builder.executionContext();
        var executionContextServiceProvider = builderExecutionContext.serviceProvider();
        var _distributedApplicationModelFromExecutionContext = executionContextServiceProvider.getDistributedApplicationModel();
        var beforeStartSubscription = builder.subscribeBeforeStart((beforeStartEvent) -> { var beforeStartServices = beforeStartEvent.services(); var beforeStartModel = beforeStartEvent.model(); var _beforeStartResources = beforeStartModel.getResources(); var _beforeStartContainer = beforeStartModel.findResourceByName("mycontainer"); var _beforeStartEventing = beforeStartServices.getEventing(); var beforeStartLoggerFactory = beforeStartServices.getLoggerFactory(); var beforeStartLogger = beforeStartLoggerFactory.createLogger("ValidationAppHost.BeforeStart"); beforeStartLogger.logInformation("BeforeStart information"); beforeStartLogger.logWarning("BeforeStart warning"); beforeStartLogger.logError("BeforeStart error"); beforeStartLogger.logDebug("BeforeStart debug"); beforeStartLogger.log("critical", "BeforeStart critical"); var beforeStartResourceLoggerService = beforeStartServices.getResourceLoggerService(); beforeStartResourceLoggerService.completeLog(new IResource(container.getHandle(), container.getClient())); beforeStartResourceLoggerService.completeLogByName("mycontainer"); var beforeStartNotificationService = beforeStartServices.getResourceNotificationService(); beforeStartNotificationService.waitForResourceState("mycontainer", "Running"); var _matchedResourceState = beforeStartNotificationService.waitForResourceStates("mycontainer", new String[] { "Running", "FailedToStart" }); var _healthyResourceEvent = beforeStartNotificationService.waitForResourceHealthy("mycontainer"); beforeStartNotificationService.waitForDependencies(new IResource(container.getHandle(), container.getClient())); var _currentResourceState = beforeStartNotificationService.tryGetResourceState("mycontainer"); beforeStartNotificationService.publishResourceUpdate(new IResource(container.getHandle(), container.getClient()), new PublishResourceUpdateOptions().state("Validated").stateStyle("info")); var userSecretsManager = beforeStartServices.getUserSecretsManager(); var _userSecretsAvailable = userSecretsManager.isAvailable(); var _userSecretsFilePath = userSecretsManager.filePath(); var _secretSet = userSecretsManager.trySetSecret("Validation:Key", "value"); userSecretsManager.getOrSetSecret(new IResource(container.getHandle(), container.getClient()), "Validation:GeneratedKey", "generated-value"); var _generatedSecretValue = builderConfiguration.getConfigValue("Validation:GeneratedKey"); userSecretsManager.saveStateJson("{\"Validation\":\"Value\"}"); var _modelFromServices = beforeStartServices.getDistributedApplicationModel(); });
        var afterResourcesCreatedSubscription = builder.subscribeAfterResourcesCreated((afterResourcesCreatedEvent) -> { var afterResourcesCreatedServices = afterResourcesCreatedEvent.services(); var afterResourcesCreatedModel = afterResourcesCreatedEvent.model(); var _afterResources = afterResourcesCreatedModel.getResources(); var _afterResourcesContainer = afterResourcesCreatedModel.findResourceByName("mycontainer"); var afterResourcesCreatedLoggerFactory = afterResourcesCreatedServices.getLoggerFactory(); var afterResourcesCreatedLogger = afterResourcesCreatedLoggerFactory.createLogger("ValidationAppHost.AfterResourcesCreated"); afterResourcesCreatedLogger.logInformation("AfterResourcesCreated"); });
        var builderEventing = builder.eventing();
        builderEventing.unsubscribe(beforeStartSubscription);
        builderEventing.unsubscribe(afterResourcesCreatedSubscription);
        container.onBeforeResourceStarted((beforeResourceStartedEvent) -> { var _resource = beforeResourceStartedEvent.resource(); var services = beforeResourceStartedEvent.services(); var loggerFactory = services.getLoggerFactory(); var logger = loggerFactory.createLogger("ValidationAppHost.BeforeResourceStarted"); logger.logInformation("BeforeResourceStarted"); });
        container.onResourceStopped((resourceStoppedEvent) -> { var _resource = resourceStoppedEvent.resource(); var services = resourceStoppedEvent.services(); var loggerFactory = services.getLoggerFactory(); var logger = loggerFactory.createLogger("ValidationAppHost.ResourceStopped"); logger.logWarning("ResourceStopped"); });
        builtConnectionString.onConnectionStringAvailable((connectionStringAvailableEvent) -> { var _resource = connectionStringAvailableEvent.resource(); var services = connectionStringAvailableEvent.services(); var notifications = services.getResourceNotificationService(); var _connectionState = notifications.tryGetResourceState("customcs"); });
        container.onInitializeResource((initializeResourceEvent) -> { var _resource = initializeResourceEvent.resource(); var _initializeEventing = initializeResourceEvent.eventing(); var initializeLogger = initializeResourceEvent.logger(); var initializeNotifications = initializeResourceEvent.notifications(); var initializeServices = initializeResourceEvent.services(); initializeLogger.logDebug("InitializeResource"); initializeNotifications.waitForDependencies(new IResource(container.getHandle(), container.getClient())); var _initializeModel = initializeServices.getDistributedApplicationModel(); var _initializeEventingFromServices = initializeServices.getEventing(); });
        container.onResourceEndpointsAllocated((resourceEndpointsAllocatedEvent) -> { var _resource = resourceEndpointsAllocatedEvent.resource(); var services = resourceEndpointsAllocatedEvent.services(); var loggerFactory = services.getLoggerFactory(); var logger = loggerFactory.createLogger("ValidationAppHost.ResourceEndpointsAllocated"); logger.logInformation("ResourceEndpointsAllocated"); });
        container.onResourceReady((resourceReadyEvent) -> { var _resource = resourceReadyEvent.resource(); var services = resourceReadyEvent.services(); var loggerFactory = services.getLoggerFactory(); var logger = loggerFactory.createLogger("ValidationAppHost.ResourceReady"); logger.logInformation("ResourceReady"); });
        container.withEnvironment("MY_VAR", "value");
        container.withEndpoint();
        container.withHttpEndpoint();
        container.withHttpsEndpoint();
        container.withExternalHttpEndpoints();
        container.asHttp2Service();
        container.withArgs(new String[] { "--verbose" });
        container.withParentRelationship(new IResource(exe.getHandle(), exe.getClient()));
        container.withExplicitStart();
        container.withUrl("http://localhost:8080");
        container.withUrlExpression(ReferenceExpression.refExpr("http://%s", endpoint));
        container.withHealthCheck("mycheck");
        container.withHttpHealthCheck();
        container.withCommand("restart", "Restart", (_ctx) -> new ExecuteCommandResult().setSuccess(true));
        var app = builder.build();
        var _distributedAppConnectionString = app.getConnectionString("customcs");
        var _distributedAppEndpoint = app.getEndpoint("dockerapp", "http");
        var _distributedAppEndpointForNetwork = app.getEndpointForNetwork("dockerapp", new GetEndpointForNetworkOptions().networkIdentifier("localhost").endpointName("http"));
        app.run();
    }
}
