---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "frontend-config"
  labels:
    app: "aspire"
    component: "frontend"
data:
  ASPNETCORE_URLS: "{{ .Values.config.frontend.ASPNETCORE_URLS }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.frontend.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.frontend.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.frontend.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.frontend.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.frontend.HTTP_PORTS }}"
  P0: "{{ .Values.config.frontend.param0 }}"
  P2: "{{ .Values.config.frontend.param2 }}"
  P3: "{{ .Values.config.frontend.param3 }}"
  services__api__http__0: "{{ .Values.config.frontend.services__api__http__0 }}"
  services__api__https__0: "{{ .Values.config.frontend.services__api__https__0 }}"
