---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "frontend-secrets"
  labels:
    app: "aspire"
    component: "frontend"
stringData:
  ConnectionStrings__sqldb: "Server=sqlserver,1433;User ID=sa;Password={{ .Values.secrets.frontend.sqlserver_password }};TrustServerCertificate=true;Initial Catalog=sqldb"
  P1: "{{ .Values.secrets.frontend.param1 }}"
type: "Opaque"
