//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class AzureKeyVaultResourceExtensions
    {
        [AspireExport("addAzureKeyVault", Description = "Adds an Azure Key Vault resource")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureKeyVaultResource> AddAzureKeyVault(this IDistributedApplicationBuilder builder, string name) { throw null; }

        [AspireExport("addSecret", Description = "Adds a secret to the Azure Key Vault from a parameter resource")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureKeyVaultSecretResource> AddSecret(this ApplicationModel.IResourceBuilder<Azure.AzureKeyVaultResource> builder, string name, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> parameterResource) { throw null; }

        [AspireExportIgnore(Reason = "Raw ParameterResource overload; use the IResourceBuilder<ParameterResource> variant instead.")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureKeyVaultSecretResource> AddSecret(this ApplicationModel.IResourceBuilder<Azure.AzureKeyVaultResource> builder, string name, ApplicationModel.ParameterResource parameterResource) { throw null; }

        [AspireExport("addSecretFromExpression", Description = "Adds a secret to the Azure Key Vault from a reference expression")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureKeyVaultSecretResource> AddSecret(this ApplicationModel.IResourceBuilder<Azure.AzureKeyVaultResource> builder, string name, ApplicationModel.ReferenceExpression value) { throw null; }

        [AspireExport("addSecretWithName", Description = "Adds a named secret to the Azure Key Vault from a parameter resource")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureKeyVaultSecretResource> AddSecret(this ApplicationModel.IResourceBuilder<Azure.AzureKeyVaultResource> builder, string name, string secretName, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> parameterResource) { throw null; }

        [AspireExportIgnore(Reason = "Raw ParameterResource overload; use the IResourceBuilder<ParameterResource> variant instead.")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureKeyVaultSecretResource> AddSecret(this ApplicationModel.IResourceBuilder<Azure.AzureKeyVaultResource> builder, string name, string secretName, ApplicationModel.ParameterResource parameterResource) { throw null; }

        [AspireExport("addSecretWithNameFromExpression", Description = "Adds a named secret to the Azure Key Vault from a reference expression")]
        public static ApplicationModel.IResourceBuilder<Azure.AzureKeyVaultSecretResource> AddSecret(this ApplicationModel.IResourceBuilder<Azure.AzureKeyVaultResource> builder, string name, string secretName, ApplicationModel.ReferenceExpression value) { throw null; }

        [AspireExport("getSecret", Description = "Gets a secret reference from the Azure Key Vault")]
        public static Azure.IAzureKeyVaultSecretReference GetSecret(this ApplicationModel.IResourceBuilder<Azure.AzureKeyVaultResource> builder, string secretName) { throw null; }

        [AspireExportIgnore(Reason = "KeyVaultBuiltInRole is an Azure.Provisioning type not compatible with ATS. Use the AzureKeyVaultRole-based overload instead.")]
        public static ApplicationModel.IResourceBuilder<T> WithRoleAssignments<T>(this ApplicationModel.IResourceBuilder<T> builder, ApplicationModel.IResourceBuilder<Azure.AzureKeyVaultResource> target, params global::Azure.Provisioning.KeyVault.KeyVaultBuiltInRole[] roles)
            where T : ApplicationModel.IResource { throw null; }
    }
}

namespace Aspire.Hosting.Azure
{
    public partial class AzureKeyVaultResource : AzureProvisioningResource, ApplicationModel.IResourceWithEndpoints, ApplicationModel.IResource, ApplicationModel.IResourceWithConnectionString, ApplicationModel.IManifestExpressionProvider, ApplicationModel.IValueProvider, ApplicationModel.IValueWithReferences, IAzureKeyVaultResource, ApplicationModel.IAzureResource, IAzurePrivateEndpointTarget
    {
        public AzureKeyVaultResource(string name, System.Action<AzureResourceInfrastructure> configureInfrastructure) : base(default!, default!) { }

        System.Func<IAzureKeyVaultSecretReference, System.Threading.CancellationToken, System.Threading.Tasks.Task<string?>>? IAzureKeyVaultResource.SecretResolver { get { throw null; } set { } }

        BicepOutputReference IAzureKeyVaultResource.VaultUriOutputReference { get { throw null; } }

        BicepOutputReference IAzurePrivateEndpointTarget.Id { get { throw null; } }

        public ApplicationModel.ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public BicepOutputReference Id { get { throw null; } }

        public bool IsEmulator { get { throw null; } }

        public BicepOutputReference NameOutputReference { get { throw null; } }

        public ApplicationModel.ReferenceExpression UriExpression { get { throw null; } }

        public BicepOutputReference VaultUri { get { throw null; } }

        public override global::Azure.Provisioning.Primitives.ProvisionableResource AddAsExistingResource(AzureResourceInfrastructure infra) { throw null; }

        System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, ApplicationModel.ReferenceExpression>> ApplicationModel.IResourceWithConnectionString.GetConnectionProperties() { throw null; }

        string IAzurePrivateEndpointTarget.GetPrivateDnsZoneName() { throw null; }

        System.Collections.Generic.IEnumerable<string> IAzurePrivateEndpointTarget.GetPrivateLinkGroupIds() { throw null; }

        public System.Threading.Tasks.ValueTask<string?> GetConnectionStringAsync(System.Threading.CancellationToken cancellationToken = default) { throw null; }

        public IAzureKeyVaultSecretReference GetSecret(string secretName) { throw null; }
    }

    [System.Diagnostics.DebuggerDisplay("Type = {GetType().Name,nq}, Name = {Name}, Secret = {SecretName}")]
    public partial class AzureKeyVaultSecretResource : ApplicationModel.Resource, ApplicationModel.IResourceWithParent<AzureKeyVaultResource>, ApplicationModel.IResourceWithParent, ApplicationModel.IResource, IAzureKeyVaultSecretReference, ApplicationModel.IValueProvider, ApplicationModel.IManifestExpressionProvider, ApplicationModel.IValueWithReferences
    {
        public AzureKeyVaultSecretResource(string name, string secretName, AzureKeyVaultResource parent, object value) : base(default!) { }

        string ApplicationModel.IManifestExpressionProvider.ValueExpression { get { throw null; } }

        IAzureKeyVaultResource IAzureKeyVaultSecretReference.Resource { get { throw null; } }

        ApplicationModel.IResource? IAzureKeyVaultSecretReference.SecretOwner { get { throw null; } set { } }

        public AzureKeyVaultResource Parent { get { throw null; } }

        public string SecretName { get { throw null; } }

        public object Value { get { throw null; } }

        System.Threading.Tasks.ValueTask<string?> ApplicationModel.IValueProvider.GetValueAsync(System.Threading.CancellationToken cancellationToken) { throw null; }
    }
}