name: 'Enumerate test projects'
description: 'Enumerate list of test projects'
inputs:
  includeTemplates:
    required: false
    type: boolean
    default: false
  includeCliE2E:
    required: false
    type: boolean
    default: false
  onlyDeploymentTests:
    required: false
    type: boolean
    default: false

# Output format: JSON with structure {"include": [{...}, ...]}
# Each entry contains:
#   - type: 'regular' | 'collection' | 'class'
#   - projectName: Full project name (e.g., 'Aspire.Hosting.Tests')
#   - name: Display name for the test run
#   - shortname: Short identifier
#   - testProjectPath: Relative path to the test project
#   - workitemprefix: Prefix for work item naming
#   - runs-on: GitHub Actions runner (e.g., 'ubuntu-latest', 'windows-latest')
#   - testSessionTimeout: Timeout for the test session (e.g., '20m')
#   - testHangTimeout: Timeout for hung tests (e.g., '10m')
#   - requiresNugets: Boolean indicating if NuGet packages are needed
#   - requiresTestSdk: Boolean indicating if test SDK is needed
#   - extraTestArgs: Additional test arguments (e.g., '--filter-trait "Partition=P1"')
#   - collection: (collection type only) Collection/partition name
#   - classname: (class type only) Fully qualified test class name
outputs:
  tests_matrix_no_nugets:
    description: Test matrix for tests that do not require NuGet packages (primary bucket)
    value: ${{ steps.generate_canonical_matrix.outputs.tests_matrix_no_nugets }}
  tests_matrix_no_nugets_overflow:
    description: Test matrix for tests that do not require NuGet packages (overflow bucket)
    value: ${{ steps.generate_canonical_matrix.outputs.tests_matrix_no_nugets_overflow }}
  tests_matrix_requires_nugets:
    description: Test matrix for tests that require NuGet packages
    value: ${{ steps.generate_canonical_matrix.outputs.tests_matrix_requires_nugets }}
  tests_matrix_requires_cli_archive:
    description: Test matrix for tests that require CLI native archives
    value: ${{ steps.generate_canonical_matrix.outputs.tests_matrix_requires_cli_archive }}
  all_tests:
    description: Combined matrix of all test entries across all buckets
    value: ${{ steps.generate_all_tests_matrix.outputs.all_tests }}
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@3951f0dfe7a07e2313ec93c75700083e2005cbab # v4.3.0
      with:
        global-json-file: ${{ github.workspace }}/global.json

    - name: Restore
      shell: bash
      run: ./restore.sh

    - name: Generate canonical test matrix
      shell: bash
      run: >
        ./build.sh -test
        /p:TestRunnerName=TestEnumerationRunsheetBuilder
        /p:TestMatrixOutputPath=artifacts/canonical-test-matrix.json
        /p:IncludeTemplateTests=${{ inputs.includeTemplates }}
        /p:IncludeCliE2ETests=${{ inputs.includeCliE2E }}
        /p:OnlyDeploymentTests=${{ inputs.onlyDeploymentTests }}
        /p:GenerateCIPartitions=true
        /bl

    - name: Expand matrix for GitHub Actions
      id: generate_canonical_matrix
      shell: pwsh
      run: |
        $canonicalMatrixPath = "${{ github.workspace }}/artifacts/canonical-test-matrix.json"
        $expandScript = "${{ github.workspace }}/eng/scripts/expand-test-matrix-github.ps1"

        if (Test-Path $canonicalMatrixPath) {
          & $expandScript -CanonicalMatrixFile $canonicalMatrixPath -OutputToGitHubEnv
        } else {
          # Empty matrices if no canonical matrix found
          $emptyMatrix = '{"include":[]}'
          "tests_matrix_no_nugets=$emptyMatrix" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          "tests_matrix_no_nugets_overflow=$emptyMatrix" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          "tests_matrix_requires_nugets=$emptyMatrix" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          "tests_matrix_requires_cli_archive=$emptyMatrix" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          Write-Host "No canonical test matrix found, using empty matrices"
        }

    - name: Generate combined all-tests matrix
      id: generate_all_tests_matrix
      shell: pwsh
      run: |
        # Combine all expanded matrix entries into a single all_tests matrix
        $allEntries = @()

        $matrixOutputs = @(
          '${{ steps.generate_canonical_matrix.outputs.tests_matrix_no_nugets }}',
          '${{ steps.generate_canonical_matrix.outputs.tests_matrix_no_nugets_overflow }}',
          '${{ steps.generate_canonical_matrix.outputs.tests_matrix_requires_nugets }}',
          '${{ steps.generate_canonical_matrix.outputs.tests_matrix_requires_cli_archive }}'
        )

        foreach ($matrixJson in $matrixOutputs) {
          if ($matrixJson -and $matrixJson -ne '{"include":[]}') {
            $matrix = $matrixJson | ConvertFrom-Json
            if ($matrix.include -and $matrix.include.Count -gt 0) {
              $allEntries += $matrix.include
            }
          }
        }

        $result = @{ include = @($allEntries) } | ConvertTo-Json -Compress -Depth 5
        Write-Host "All tests matrix ($($allEntries.Count) entries): $result"
        "all_tests=$result" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
      with:
        name: logs-enumerate-tests-${{ runner.os }}
        path: |
          artifacts/log/**/*.binlog
          artifacts/**/*tests-partitions.json
          artifacts/**/*tests-metadata.json
          artifacts/canonical-test-matrix.json
