name: 'Enumerate test projects'
description: 'Enumerate list of test projects'
inputs:
  includeIntegrations:
    required: false
    type: boolean
    default: false
  includeTemplates:
    required: false
    type: boolean
    default: false
  includeCliE2E:
    required: false
    type: boolean
    default: false
  integrationsProjectsFilter:
    description: 'JSON array of specific integration test project paths to run. Empty array or not provided means run all.'
    required: false
    type: string
    default: '[]'

outputs:
  integrations_tests_matrix:
    description: Integration tests matrix
    value: ${{ steps.generate_integrations_matrix.outputs.integrations_tests_matrix }}
  templates_tests_matrix:
    description: Templates tests matrix
    value: ${{ steps.generate_templates_matrix.outputs.templates_tests_matrix }}
  cli_e2e_tests_matrix:
    description: Cli E2E tests matrix
    value: ${{ steps.generate_cli_e2e_matrix.outputs.cli_e2e_tests_matrix }}
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@3951f0dfe7a07e2313ec93c75700083e2005cbab # v4.3.0
      with:
        global-json-file: ${{ github.workspace }}/global.json

    - name: Get list of integration tests
      if: ${{ inputs.includeIntegrations }}
      shell: pwsh
      run: >
        dotnet build ${{ github.workspace }}/tests/Shared/GetTestProjects.proj
        /bl:${{ github.workspace }}/artifacts/log/Debug/GetTestProjects.binlog
        /p:TestsListOutputPath=${{ github.workspace }}/artifacts/TestsForGithubActions.list
        /p:ContinuousIntegrationBuild=true

    - name: Generate list of template tests
      if: ${{ inputs.includeTemplates }}
      shell: pwsh
      run: >
          dotnet build ${{ github.workspace }}/tests/Aspire.Templates.Tests/Aspire.Templates.Tests.csproj
          "/t:Build;ExtractTestClassNames"
          /bl:${{ github.workspace }}/artifacts/log/Debug/BuildTemplatesTests.binlog
          -p:ExtractTestClassNamesForHelix=true
          -p:PrepareForHelix=true
          -p:ExtractTestClassNamesPrefix=Aspire.Templates.Tests
          -p:InstallBrowsersForPlaywright=false

    - name: Generate list of CLI E2E tests
      if: ${{ inputs.includeCliE2E }}
      shell: pwsh
      run: >
          dotnet build ${{ github.workspace }}/tests/Aspire.Cli.EndToEnd.Tests/Aspire.Cli.EndToEnd.Tests.csproj
          "/t:Build;ExtractTestClassNames"
          /bl:${{ github.workspace }}/artifacts/log/Debug/BuildCliEndToEndTests.binlog
          -p:ExtractTestClassNamesForHelix=true
          -p:PrepareForHelix=true
          -p:ExtractTestClassNamesPrefix=Aspire.Cli.EndToEnd.Tests
          -p:InstallBrowsersForPlaywright=false

    - name: Generate tests matrix
      id: generate_integrations_matrix
      if: ${{ inputs.includeIntegrations }}
      shell: pwsh
      run: |
        $filePath = "${{ github.workspace }}/artifacts/TestsForGithubActions.list"
        $lines = @(Get-Content $filePath)

        # Filter to specific projects if provided
        $projectsFilter = '${{ inputs.integrationsProjectsFilter }}'
        if ($projectsFilter -and $projectsFilter -ne '' -and $projectsFilter -ne '[]') {
            $projects = $projectsFilter | ConvertFrom-Json

            # Convert project paths to shortnames
            # e.g., "tests/Aspire.Milvus.Client.Tests/" -> "Milvus.Client"
            $allowedShortnames = @()
            foreach ($project in $projects) {
                # Extract directory name from path (handle trailing slash)
                $dirName = ($project -replace '/$', '') -split '/' | Select-Object -Last 1
                # Convert to shortname: Aspire.Milvus.Client.Tests -> Milvus.Client
                $shortname = $dirName -replace '^Aspire\.', '' -replace '\.Tests$', ''
                $allowedShortnames += $shortname
            }

            if ($allowedShortnames.Count -gt 0) {
                Write-Host "Filtering integration tests to: $($allowedShortnames -join ', ')"
                $lines = @($lines | Where-Object { $_ -in $allowedShortnames })
                Write-Host "Filtered to $($lines.Count) test(s)"
            }
        }

        $jsonObject = @{
            "shortname" = @($lines | Sort-Object)
        }
        $jsonString = ConvertTo-Json $jsonObject -Compress
        "integrations_tests_matrix=$jsonString"
        "integrations_tests_matrix=$jsonString" | Out-File -FilePath $env:GITHUB_OUTPUT

    - name: Generate templates matrix
      id: generate_templates_matrix
      if: ${{ inputs.includeTemplates }}
      shell: pwsh
      run: |
        $inputFilePath = "${{ github.workspace }}/artifacts/helix/templates-tests/Aspire.Templates.Tests.tests.list"
        $lines = Get-Content $inputFilePath

        $prefix = "Aspire.Templates.Tests."
        $lines = Get-Content $inputFilePath | ForEach-Object {
            $_ -replace "^$prefix", ""
        }

        $jsonObject = @{
            "shortname" = $lines | Sort-Object
        }
        $jsonString = ConvertTo-Json $jsonObject -Compress
        "templates_tests_matrix=$jsonString"
        "templates_tests_matrix=$jsonString" | Out-File -FilePath $env:GITHUB_OUTPUT

    - name: Generate cli e2e matrix
      id: generate_cli_e2e_matrix
      if: ${{ inputs.includeCliE2E }}
      shell: pwsh
      run: |
        $inputFilePath = "${{ github.workspace }}/artifacts/helix/cli-e2e-tests/Aspire.Cli.EndToEnd.Tests.tests.list"
        $lines = Get-Content $inputFilePath

        $prefix = "Aspire.Cli.EndToEnd.Tests."
        $lines = @(Get-Content $inputFilePath | ForEach-Object {
            $_ -replace "^$prefix", ""
        })

        $jsonObject = @{
            "shortname" = @($lines | Sort-Object)
        }
        $jsonString = ConvertTo-Json $jsonObject -Compress
        "cli_e2e_tests_matrix=$jsonString"
        "cli_e2e_tests_matrix=$jsonString" | Out-File -FilePath $env:GITHUB_OUTPUT

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
      with:
        name: logs-enumerate-tests-${{ runner.os }}
        path: |
          artifacts/log/**/*.binlog
          artifacts/**/*.list
