name: 'Enumerate test projects'
description: 'Enumerate list of test projects'
inputs:
  includeTemplates:
    required: false
    type: boolean
    default: false
  includeCliE2E:
    required: false
    type: boolean
    default: false
  includeDeployment:
    required: false
    type: boolean
    default: false

# Output format: JSON with structure {"include": [{...}, ...]}
# Each entry contains:
#   - type: 'regular' | 'collection' | 'class'
#   - projectName: Full project name (e.g., 'Aspire.Hosting.Tests')
#   - name: Display name for the test run
#   - shortname: Short identifier
#   - testProjectPath: Relative path to the test project
#   - workitemprefix: Prefix for work item naming
#   - runs-on: GitHub Actions runner (e.g., 'ubuntu-latest', 'windows-latest')
#   - testSessionTimeout: Timeout for the test session (e.g., '20m')
#   - testHangTimeout: Timeout for hung tests (e.g., '10m')
#   - requiresNugets: Boolean indicating if NuGet packages are needed
#   - requiresTestSdk: Boolean indicating if test SDK is needed
#   - extraTestArgs: Additional test arguments (e.g., '--filter-trait "Partition=P1"')
#   - collection: (collection type only) Collection/partition name
#   - classname: (class type only) Fully qualified test class name
outputs:
  tests_matrix:
    description: Canonical tests matrix for all tests
    value: ${{ steps.generate_canonical_matrix.outputs.tests_matrix }}
  deployment_tests_matrix:
    description: Deployment E2E tests matrix
    value: ${{ steps.generate_deployment_matrix.outputs.deployment_tests_matrix }}
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@3951f0dfe7a07e2313ec93c75700083e2005cbab # v4.3.0
      with:
        global-json-file: ${{ github.workspace }}/global.json

    - name: Restore
      shell: bash
      run: ./restore.sh

    - name: Generate canonical test matrix
      shell: bash
      run: >
        ./build.sh -test
        /p:TestRunnerName=TestEnumerationRunsheetBuilder
        /p:TestMatrixOutputPath=artifacts/canonical-test-matrix.json
        /p:IncludeTemplateTests=${{ inputs.includeTemplates }}
        /p:IncludeCliE2ETests=${{ inputs.includeCliE2E }}
        /p:GenerateCIPartitions=true
        /bl

    - name: Generate list of Deployment E2E tests
      if: ${{ inputs.includeDeployment == 'true' }}
      shell: pwsh
      run: >
        dotnet build ${{ github.workspace }}/tests/Aspire.Deployment.EndToEnd.Tests/Aspire.Deployment.EndToEnd.Tests.csproj
        "/t:Build;GenerateTestPartitionsForCI"
        /p:GenerateCIPartitions=true
        /bl:${{ github.workspace }}/artifacts/log/Debug/BuildDeploymentEndToEndTests.binlog

    - name: Generate deployment matrix
      id: generate_deployment_matrix
      if: ${{ inputs.includeDeployment == 'true' }}
      shell: pwsh
      run: |
        # Find the partitions JSON generated by GenerateTestPartitionsForCI
        $partitionsFile = Get-ChildItem -Path "${{ github.workspace }}/artifacts" -Filter "Aspire.Deployment.EndToEnd.Tests.tests-partitions.json" -Recurse | Select-Object -First 1

        if (-not $partitionsFile) {
          Write-Error "Deployment test partitions JSON not found"
          exit 1
        }

        Write-Host "Reading partitions from: $($partitionsFile.FullName)"
        $partitionsJson = Get-Content -Raw -Path $partitionsFile.FullName | ConvertFrom-Json

        $prefix = "Aspire.Deployment.EndToEnd.Tests."
        $shortnames = @($partitionsJson.testPartitions | ForEach-Object {
            # Strip "class:" prefix and namespace prefix
            $_ -replace '^class:', '' -replace "^$([Regex]::Escape($prefix))", ''
        } | Sort-Object)

        $jsonObject = @{
            "shortname" = @($shortnames)
        }
        $jsonString = ConvertTo-Json $jsonObject -Compress
        "deployment_tests_matrix=$jsonString"
        "deployment_tests_matrix=$jsonString" | Out-File -FilePath $env:GITHUB_OUTPUT

    - name: Expand matrix for GitHub Actions
      id: generate_canonical_matrix
      shell: pwsh
      run: |
        $canonicalMatrixPath = "${{ github.workspace }}/artifacts/canonical-test-matrix.json"
        $expandScript = "${{ github.workspace }}/eng/scripts/expand-test-matrix-github.ps1"

        if (Test-Path $canonicalMatrixPath) {
          & $expandScript -CanonicalMatrixFile $canonicalMatrixPath -OutputToGitHubEnv
        } else {
          # Empty matrix if no canonical matrix found
          $emptyMatrix = '{"include":[]}'
          "tests_matrix=$emptyMatrix" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          Write-Host "No canonical test matrix found, using empty matrix"
        }

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
      with:
        name: logs-enumerate-tests-${{ runner.os }}
        path: |
          artifacts/log/**/*.binlog
          artifacts/**/*tests-partitions.json
          artifacts/**/*tests-metadata.json
          artifacts/canonical-test-matrix.json
