name: 'Enumerate test projects'
description: 'Enumerate list of test projects'
inputs:
  includeIntegrations:
    required: false
    type: boolean
    default: false
  includeTemplates:
    required: false
    type: boolean
    default: false

outputs:
  integrations_tests_matrix:
    description: Integration tests matrix
    value: ${{ steps.generate_integrations_matrix.outputs.integrations_tests_matrix }}
  templates_tests_matrix:
    description: Templates tests matrix
    value: ${{ steps.generate_templates_matrix.outputs.templates_tests_matrix }}
  split_tests_matrix:
    description: Split tests matrix (for collection/class-based splitting)
    value: ${{ steps.generate_split_tests_matrix.outputs.split_tests_matrix }}
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@3951f0dfe7a07e2313ec93c75700083e2005cbab # v4.3.0
      with:
        global-json-file: ${{ github.workspace }}/global.json

    - name: Get list of integration tests
      if: ${{ inputs.includeIntegrations }}
      shell: pwsh
      run: >
        dotnet build ${{ github.workspace }}/tests/Shared/GetTestProjects.proj
        /bl:${{ github.workspace }}/artifacts/log/Debug/GetTestProjects.binlog
        /p:TestsListOutputPath=${{ github.workspace }}/artifacts/TestsForGithubActions.list
        /p:TestMatrixOutputPath=${{ github.workspace }}/artifacts/test-matrices/
        /p:ContinuousIntegrationBuild=true
        /p:BuildOs=${{ runner.os == 'Linux' && 'linux' || runner.os == 'macOS' && 'darwin' || 'windows' }}

    - name: Generate list of template tests
      if: ${{ inputs.includeTemplates }}
      shell: pwsh
      run: >
          dotnet build ${{ github.workspace }}/tests/Aspire.Templates.Tests/Aspire.Templates.Tests.csproj
          "/t:Build;ExtractTestClassNames"
          /bl:${{ github.workspace }}/artifacts/log/Debug/BuildTemplatesTests.binlog
          -p:ExtractTestClassNamesForHelix=true
          -p:PrepareForHelix=true
          -p:ExtractTestClassNamesPrefix=Aspire.Templates.Tests
          -p:InstallBrowsersForPlaywright=false

    - name: Generate tests matrix
      id: generate_integrations_matrix
      if: ${{ inputs.includeIntegrations }}
      shell: pwsh
      run: |
        $filePath = "${{ github.workspace }}/artifacts/TestsForGithubActions.list"
        $lines = Get-Content $filePath
        $jsonObject = @{
            "shortname" = $lines | Sort-Object
        }
        $jsonString = ConvertTo-Json $jsonObject -Compress
        "integrations_tests_matrix=$jsonString"
        "integrations_tests_matrix=$jsonString" | Out-File -FilePath $env:GITHUB_OUTPUT

    - name: Generate templates matrix
      id: generate_templates_matrix
      if: ${{ inputs.includeTemplates }}
      shell: pwsh
      run: |
        $inputFilePath = "${{ github.workspace }}/artifacts/helix/templates-tests/Aspire.Templates.Tests.tests.list"
        $lines = Get-Content $inputFilePath

        $prefix = "Aspire.Templates.Tests."
        $lines = Get-Content $inputFilePath | ForEach-Object {
            $_ -replace "^$prefix", ""
        }

        $jsonObject = @{
            "shortname" = $lines | Sort-Object
        }
        $jsonString = ConvertTo-Json $jsonObject -Compress
        "templates_tests_matrix=$jsonString"
        "templates_tests_matrix=$jsonString" | Out-File -FilePath $env:GITHUB_OUTPUT

    - name: Generate split tests matrix
      id: generate_split_tests_matrix
      if: ${{ inputs.includeIntegrations }}
      shell: pwsh
      run: |
        $matrixFilePath = "${{ github.workspace }}/artifacts/test-matrices/split-tests-matrix.json"
        if (Test-Path $matrixFilePath) {
          $matrixContent = Get-Content -Raw $matrixFilePath
          # Validate it's valid JSON
          $null = $matrixContent | ConvertFrom-Json
          "split_tests_matrix=$matrixContent" | Out-File -FilePath $env:GITHUB_OUTPUT
          Write-Host "Split tests matrix generated successfully"
        } else {
          # Empty matrix if no split tests
          $emptyMatrix = '{"include":[]}'
          "split_tests_matrix=$emptyMatrix" | Out-File -FilePath $env:GITHUB_OUTPUT
          Write-Host "No split tests matrix found, using empty matrix"
        }

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
      with:
        name: logs-enumerate-tests-${{ runner.os }}
        path: |
          artifacts/log/**/*.binlog
          artifacts/**/*.list
