name: 'Enumerate test projects'
description: 'Enumerate list of test projects'
inputs:
  buildArgs:
    required: false
    type: string
    default: ''
    description: 'Additional MSBuild arguments passed to the test matrix generation step (e.g., /p:IncludeTemplateTests=true /p:OnlyDeploymentTests=true)'

# Output format: JSON with structure {"include": [{...}, ...]}
# Each entry contains:
#   - type: 'regular' | 'collection' | 'class'
#   - projectName: Full project name (e.g., 'Aspire.Hosting.Tests')
#   - name: Display name for the test run
#   - shortname: Short identifier
#   - testProjectPath: Relative path to the test project
#   - workitemprefix: Prefix for work item naming
#   - runs-on: GitHub Actions runner (e.g., 'ubuntu-latest', 'windows-latest')
#   - testSessionTimeout: Timeout for the test session (e.g., '20m')
#   - testHangTimeout: Timeout for hung tests (e.g., '10m')
#   - requiresNugets: Boolean indicating if NuGet packages are needed
#   - requiresTestSdk: Boolean indicating if test SDK is needed
#   - extraTestArgs: Additional test arguments (e.g., '--filter-trait "Partition=P1"')
#   - collection: (collection type only) Collection/partition name
#   - classname: (class type only) Fully qualified test class name
outputs:
  all_tests:
    description: Combined matrix of all test entries
    value: ${{ steps.expand_matrix.outputs.all_tests }}
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@3951f0dfe7a07e2313ec93c75700083e2005cbab # v4.3.0
      with:
        global-json-file: ${{ github.workspace }}/global.json

    - name: Restore
      shell: bash
      run: ./restore.sh

    - name: Generate canonical test matrix
      shell: bash
      run: >
        ./build.sh -test
        /p:TestRunnerName=TestEnumerationRunsheetBuilder
        /p:TestMatrixOutputPath=artifacts/canonical-test-matrix.json
        /p:GenerateCIPartitions=true
        /bl
        ${{ inputs.buildArgs }}

    - name: Expand matrix for GitHub Actions
      id: expand_matrix
      shell: pwsh
      run: |
        $canonicalMatrixPath = "${{ github.workspace }}/artifacts/canonical-test-matrix.json"
        $expandScript = "${{ github.workspace }}/eng/scripts/expand-test-matrix-github.ps1"

        if (Test-Path $canonicalMatrixPath) {
          & $expandScript -CanonicalMatrixFile $canonicalMatrixPath -OutputToGitHubEnv
        } else {
          $emptyMatrix = '{"include":[]}'
          "all_tests=$emptyMatrix" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          Write-Host "No canonical test matrix found, using empty matrix"
        }

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
      with:
        name: logs-enumerate-tests-${{ runner.os }}
        path: |
          artifacts/log/**/*.binlog
          artifacts/**/*tests-partitions.json
          artifacts/**/*tests-metadata.json
          artifacts/canonical-test-matrix.json
