name: 'Enumerate test projects'
description: 'Enumerate list of test projects'
outputs:
  integrations_tests_matrix:
    description: tests matrix
    value: ${{ steps.generate_test_matrix.outputs.integrations_tests_matrix }}
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@3951f0dfe7a07e2313ec93c75700083e2005cbab # v4.3.0
      with:
        dotnet-version: |
          9.x

    - name: Get list of tests
      env:
        CI: false
      shell: pwsh
      run: >
        dotnet build ${{ github.workspace }}/tests/Shared/GetTestProjects.proj
        /p:TestsListOutputPath=${{ github.workspace }}/artifacts/TestsForGithubActions.list
        /p:ContinuousIntegrationBuild=true

    - name: Generate tests matrix
      id: generate_test_matrix
      shell: pwsh
      env:
        CI: false
      run: |
        $filePath = "${{ github.workspace }}/artifacts/TestsForGithubActions.list"
        $lines = Get-Content $filePath
        $jsonObject = @{
            "shortname" = $lines | Sort-Object
        }
        $jsonString = ConvertTo-Json $jsonObject -Compress
        "integrations_tests_matrix=$jsonString"
        "integrations_tests_matrix=$jsonString" | Out-File -FilePath $env:GITHUB_OUTPUT
