eventResponderTasks

id: eventResponderTask.GithubActionPROpened
name: Close and re-open PRs opened via Github Action
description: Closes and re-open PRs opened via Github Action
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
    - if:
      - payloadType: Pull_Request
      - isAction:
          action: Opened
      - isActivitySender:
          user: github-actions[bot]
          issueAuthor: False
      then:
      - addLabel:
          label: 'Closed Github-Action PR'
      - closeIssue
      description: Close and label Github-Action PRs
      - if:
        - payloadType: Pull_Request
        - isAction:
            action: Closed
        - hasLabel:
            label: 'Closed Github-Action PR'
        then:
        - removeLabel:
            label: 'Closed Github-Action PR'
        - reopenIssue
        description: Reopen closed Github-Action PRs