id: labelManagement.issueOpened
name: New Issues
description: Adds information when PRs are opened
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: Add CodeFlow link to new PRs
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Opened
        then:
          - addCodeFlowLink
      - description: Add Servicing-consider label to PRs against release branches
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Opened
          - not:
              hasLabel:
                label: Servicing-consider
          - targetsBranch:
              branch: release/8.0
        then:
          - addLabel:
              label: Servicing-consider
      - description: Add untriaged to new issues
        if:
          - payloadType: Issues
          - isAction:
            action: Opened
        then:
          - addLabel:
              label: untriaged
