//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class OpenAIExtensions
    {
        public static ApplicationModel.IResourceBuilder<OpenAI.OpenAIModelResource> AddOpenAIModel(this IDistributedApplicationBuilder builder, string name, string model) { throw null; }

        public static ApplicationModel.IResourceBuilder<OpenAI.OpenAIModelResource> WithApiKey(this ApplicationModel.IResourceBuilder<OpenAI.OpenAIModelResource> builder, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> apiKey) { throw null; }

        public static ApplicationModel.IResourceBuilder<OpenAI.OpenAIModelResource> WithHealthCheck(this ApplicationModel.IResourceBuilder<OpenAI.OpenAIModelResource> builder) { throw null; }
    }
}

namespace Aspire.Hosting.OpenAI
{
    public partial class OpenAIModelResource : ApplicationModel.Resource, ApplicationModel.IResourceWithConnectionString, ApplicationModel.IResource, ApplicationModel.IManifestExpressionProvider, ApplicationModel.IValueProvider, ApplicationModel.IValueWithReferences, ApplicationModel.IResourceWithoutLifetime
    {
        public OpenAIModelResource(string name, string model, ApplicationModel.ParameterResource key) : base(default!) { }

        public ApplicationModel.ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public ApplicationModel.ParameterResource Key { get { throw null; } }

        public string Model { get { throw null; } set { } }
    }
}
