name: 'Cache .NET SDK for Arcade'
description: |
  Aggressively cache the .NET SDK in the .dotnet directory using actions/cache@v4.

  This action caches the .dotnet directory and only runs SDK installation on cache misses.
  It uses a minimal empty project file with Arcade's build infrastructure to trigger SDK
  installation without building any actual code.

  The cache key includes global.json and eng/Versions.props to ensure the cache is
  invalidated when SDK versions, runtime versions.

  Why we can't use actions/setup-dotnet:
  The Aspire repository has complex requirements in global.json that include:
  - Custom SDK paths pointing to local .dotnet directory
  - Multiple runtime versions with variable substitution (e.g., $(DotNetRuntimePreviousVersionForTesting))
  - Architecture-specific runtimes (x64, arm64) for different platforms
  - Custom error messages for missing SDK

  The actions/setup-dotnet action doesn't support these advanced global.json features,
  particularly the "paths" array and variable substitution in the "runtimes" section.
  Instead, we use the repository's Arcade build infrastructure (eng/build.ps1 or build.sh)
  which properly handles these requirements and installs SDKs to the local .dotnet directory.

inputs:
  key-prefix:
    description: 'Prefix for the cache key'
    required: false
    default: 'dotnet-sdk-v1'

outputs:
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the cache-key'
    value: ${{ steps.cache-dotnet.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Cache .dotnet directory
      id: cache-dotnet
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: .dotnet
        key: ${{ inputs.key-prefix }}-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('global.json', 'eng/Versions.props') }}

    - name: Install Sdks (Windows)
      if: steps.cache-dotnet.outputs.cache-hit != 'true' && runner.os == 'Windows'
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Path ./artifacts/tmp -Force | Out-Null
        '<Project />' | Out-File -FilePath ./artifacts/tmp/install-sdks.proj -Encoding utf8
        ./eng/build.ps1 -restore -projects ./artifacts/tmp/install-sdks.proj
        Remove-Item -Path ./artifacts/tmp/install-sdks.proj -Force

    - name: Install Sdks (Linux/macOS)
      if: steps.cache-dotnet.outputs.cache-hit != 'true' && runner.os != 'Windows'
      shell: bash
      run: |
        mkdir -p ./artifacts/tmp
        echo '<Project />' > ./artifacts/tmp/install-sdks.proj
        ./build.sh -restore -projects $PWD/artifacts/tmp/install-sdks.proj
        rm -f ./artifacts/tmp/install-sdks.proj
