//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class MauiAndroidExtensions
    {
        public static ApplicationModel.IResourceBuilder<Maui.MauiAndroidDeviceResource> AddAndroidDevice(this ApplicationModel.IResourceBuilder<Maui.MauiProjectResource> builder) { throw null; }

        public static ApplicationModel.IResourceBuilder<Maui.MauiAndroidDeviceResource> AddAndroidDevice(this ApplicationModel.IResourceBuilder<Maui.MauiProjectResource> builder, string name) { throw null; }

        public static ApplicationModel.IResourceBuilder<Maui.MauiAndroidDeviceResource> AddAndroidDevice(this ApplicationModel.IResourceBuilder<Maui.MauiProjectResource> builder, string name, string? deviceId = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<Maui.MauiAndroidEmulatorResource> AddAndroidEmulator(this ApplicationModel.IResourceBuilder<Maui.MauiProjectResource> builder) { throw null; }

        public static ApplicationModel.IResourceBuilder<Maui.MauiAndroidEmulatorResource> AddAndroidEmulator(this ApplicationModel.IResourceBuilder<Maui.MauiProjectResource> builder, string name) { throw null; }

        public static ApplicationModel.IResourceBuilder<Maui.MauiAndroidEmulatorResource> AddAndroidEmulator(this ApplicationModel.IResourceBuilder<Maui.MauiProjectResource> builder, string name, string? emulatorId = null) { throw null; }
    }

    public static partial class MauiMacCatalystExtensions
    {
        public static ApplicationModel.IResourceBuilder<Maui.MauiMacCatalystPlatformResource> AddMacCatalystDevice(this ApplicationModel.IResourceBuilder<Maui.MauiProjectResource> builder, string name) { throw null; }

        public static ApplicationModel.IResourceBuilder<Maui.MauiMacCatalystPlatformResource> AddMacCatalystDevice(this ApplicationModel.IResourceBuilder<Maui.MauiProjectResource> builder) { throw null; }
    }

    public static partial class MauiOtlpExtensions
    {
        public static ApplicationModel.IResourceBuilder<T> WithOtlpDevTunnel<T>(this ApplicationModel.IResourceBuilder<T> builder) where T : Maui.IMauiPlatformResource { throw null; }
    }

    public static partial class MauiProjectExtensions
    {
        public static ApplicationModel.IResourceBuilder<Maui.MauiProjectResource> AddMauiProject(this IDistributedApplicationBuilder builder, string name, string projectPath) { throw null; }
    }

    public static partial class MauiWindowsExtensions
    {
        public static ApplicationModel.IResourceBuilder<Maui.MauiWindowsPlatformResource> AddWindowsDevice(this ApplicationModel.IResourceBuilder<Maui.MauiProjectResource> builder, string name) { throw null; }

        public static ApplicationModel.IResourceBuilder<Maui.MauiWindowsPlatformResource> AddWindowsDevice(this ApplicationModel.IResourceBuilder<Maui.MauiProjectResource> builder) { throw null; }
    }
}

namespace Aspire.Hosting.Maui
{
    public partial interface IMauiPlatformResource : ApplicationModel.IResourceWithParent<MauiProjectResource>, ApplicationModel.IResourceWithParent, ApplicationModel.IResource
    {
    }

    public partial class MauiAndroidDeviceResource : ApplicationModel.ProjectResource, IMauiPlatformResource, ApplicationModel.IResourceWithParent<MauiProjectResource>, ApplicationModel.IResourceWithParent, ApplicationModel.IResource
    {
        public MauiAndroidDeviceResource(string name, MauiProjectResource parent) : base(default!) { }

        public MauiProjectResource Parent { get { throw null; } }
    }

    public partial class MauiAndroidEmulatorResource : ApplicationModel.ProjectResource, IMauiPlatformResource, ApplicationModel.IResourceWithParent<MauiProjectResource>, ApplicationModel.IResourceWithParent, ApplicationModel.IResource
    {
        public MauiAndroidEmulatorResource(string name, MauiProjectResource parent) : base(default!) { }

        public MauiProjectResource Parent { get { throw null; } }
    }

    public partial class MauiMacCatalystPlatformResource : ApplicationModel.ProjectResource, IMauiPlatformResource, ApplicationModel.IResourceWithParent<MauiProjectResource>, ApplicationModel.IResourceWithParent, ApplicationModel.IResource
    {
        public MauiMacCatalystPlatformResource(string name, MauiProjectResource parent) : base(default!) { }

        public MauiProjectResource Parent { get { throw null; } }
    }

    public partial class MauiProjectResource : ApplicationModel.Resource
    {
        public MauiProjectResource(string name, string projectPath) : base(default!) { }

        public string ProjectPath { get { throw null; } }
    }

    public partial class MauiWindowsPlatformResource : ApplicationModel.ProjectResource, IMauiPlatformResource, ApplicationModel.IResourceWithParent<MauiProjectResource>, ApplicationModel.IResourceWithParent, ApplicationModel.IResource
    {
        public MauiWindowsPlatformResource(string name, MauiProjectResource parent) : base(default!) { }

        public MauiProjectResource Parent { get { throw null; } }
    }
}
