//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class AzureLogAnalyticsWorkspaceExtensions
    {
        public static ApplicationModel.IResourceBuilder<Azure.AzureLogAnalyticsWorkspaceResource> AddAzureLogAnalyticsWorkspace(this IDistributedApplicationBuilder builder, string name) { throw null; }
    }
}

namespace Aspire.Hosting.Azure
{
    public partial class AzureLogAnalyticsWorkspaceResource : AzureProvisioningResource
    {
        public AzureLogAnalyticsWorkspaceResource(string name, System.Action<AzureResourceInfrastructure> configureInfrastructure) : base(default!, default!) { }

        public BicepOutputReference WorkspaceId { get { throw null; } }
    }
}