// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Diagnostics;

namespace Aspire.Hosting.ApplicationModel;

/// <summary>
/// Represents an annotation that overrides the default project launch arguments
/// generated by DCP for a <see cref="ProjectResource"/>.
/// </summary>
/// <remarks>
/// When this annotation is present on a <see cref="ProjectResource"/>, DCP will use the provided
/// arguments instead of the default <c>run --project X --configuration Debug --no-launch-profile</c>
/// arguments. This is useful for MAUI projects that need to use <c>build /t:Run</c> instead of
/// <c>dotnet run</c>.
/// </remarks>
[DebuggerDisplay("Type = {GetType().Name,nq}, Args = {string.Join(\" \", Args)}")]
public sealed class ProjectLaunchArgsOverrideAnnotation(IReadOnlyList<string> args) : IResourceAnnotation
{
    /// <summary>
    /// Gets the custom launch arguments to use instead of the default project args.
    /// </summary>
    public IReadOnlyList<string> Args { get; } = args;
}
