//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class SqlServerBuilderExtensions
    {
        [AspireExport("addDatabase", Description = "Adds a SQL Server database resource")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.SqlServerDatabaseResource> AddDatabase(this ApplicationModel.IResourceBuilder<ApplicationModel.SqlServerServerResource> builder, string name, string? databaseName = null) { throw null; }

        [AspireExport("addSqlServer", Description = "Adds a SQL Server container resource")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.SqlServerServerResource> AddSqlServer(this IDistributedApplicationBuilder builder, string name, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource>? password = null, int? port = null) { throw null; }

        [AspireExport("withCreationScript", Description = "Defines the SQL script used to create the database")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.SqlServerDatabaseResource> WithCreationScript(this ApplicationModel.IResourceBuilder<ApplicationModel.SqlServerDatabaseResource> builder, string script) { throw null; }

        [AspireExport("withDataBindMount", Description = "Adds a bind mount for the SQL Server data folder")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.SqlServerServerResource> WithDataBindMount(this ApplicationModel.IResourceBuilder<ApplicationModel.SqlServerServerResource> builder, string source, bool isReadOnly = false) { throw null; }

        [AspireExport("withDataVolume", Description = "Adds a named volume for the SQL Server data folder")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.SqlServerServerResource> WithDataVolume(this ApplicationModel.IResourceBuilder<ApplicationModel.SqlServerServerResource> builder, string? name = null, bool isReadOnly = false) { throw null; }

        [AspireExport("withHostPort", Description = "Sets the host port for the SQL Server resource")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.SqlServerServerResource> WithHostPort(this ApplicationModel.IResourceBuilder<ApplicationModel.SqlServerServerResource> builder, int? port) { throw null; }

        [AspireExport("withPassword", Description = "Configures the password for the SQL Server resource")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.SqlServerServerResource> WithPassword(this ApplicationModel.IResourceBuilder<ApplicationModel.SqlServerServerResource> builder, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> password) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    [System.Diagnostics.DebuggerDisplay("Type = {GetType().Name,nq}, Name = {Name}, Database = {DatabaseName}")]
    public partial class SqlServerDatabaseResource : Resource, IResourceWithParent<SqlServerServerResource>, IResourceWithParent, IResource, IResourceWithConnectionString, IManifestExpressionProvider, IValueProvider, IValueWithReferences
    {
        public SqlServerDatabaseResource(string name, string databaseName, SqlServerServerResource parent) : base(default!) { }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public string DatabaseName { get { throw null; } }

        public ReferenceExpression JdbcConnectionString { get { throw null; } }

        public SqlServerServerResource Parent { get { throw null; } }

        public ReferenceExpression UriExpression { get { throw null; } }

        System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, ReferenceExpression>> IResourceWithConnectionString.GetConnectionProperties() { throw null; }
    }

    public partial class SqlServerServerResource : ContainerResource, IResourceWithConnectionString, IResource, IManifestExpressionProvider, IValueProvider, IValueWithReferences
    {
        public SqlServerServerResource(string name, ParameterResource password) : base(default!, default) { }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public System.Collections.Generic.IReadOnlyDictionary<string, string> Databases { get { throw null; } }

        public EndpointReferenceExpression Host { get { throw null; } }

        public ReferenceExpression JdbcConnectionString { get { throw null; } }

        public ParameterResource PasswordParameter { get { throw null; } }

        public EndpointReferenceExpression Port { get { throw null; } }

        public EndpointReference PrimaryEndpoint { get { throw null; } }

        public ReferenceExpression UriExpression { get { throw null; } }

        public ReferenceExpression UserNameReference { get { throw null; } }

        System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, ReferenceExpression>> IResourceWithConnectionString.GetConnectionProperties() { throw null; }

        public System.Threading.Tasks.ValueTask<string?> GetConnectionStringAsync(System.Threading.CancellationToken cancellationToken = default) { throw null; }
    }
}