//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AgentCommandStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AgentCommandStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.AgentCommandStrings", typeof(AgentCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage AI agent environment configuration..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the MCP (Model Context Protocol) server..
        /// </summary>
        internal static string McpCommand_Description {
            get {
                return ResourceManager.GetString("McpCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize agent environment configuration for detected agents..
        /// </summary>
        internal static string InitCommand_Description {
            get {
                return ResourceManager.GetString("InitCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0} config to use new 'agent mcp' command.
        /// </summary>
        internal static string DeprecatedConfigUpdate_Description {
            get {
                return ResourceManager.GetString("DeprecatedConfigUpdate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} config uses deprecated 'mcp start' command.
        /// </summary>
        internal static string DeprecatedConfigWarning {
            get {
                return ResourceManager.GetString("DeprecatedConfigWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run 'aspire agent init' to update configuration.
        /// </summary>
        internal static string DeprecatedConfigFix {
            get {
                return ResourceManager.GetString("DeprecatedConfigFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following agent configurations use the deprecated 'mcp start' command. Update them?.
        /// </summary>
        internal static string ConfigUpdatesSelectPrompt {
            get {
                return ResourceManager.GetString("ConfigUpdatesSelectPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file '{0}' contains malformed JSON. Please fix the file manually and re-run the command..
        /// </summary>
        internal static string MalformedConfigFileError {
            get {
                return ResourceManager.GetString("MalformedConfigFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping update of '{0}'..
        /// </summary>
        internal static string SkippedMalformedConfigFile {
            get {
                return ResourceManager.GetString("SkippedMalformedConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration completed with errors. Please fix the reported issues and re-run the command..
        /// </summary>
        internal static string ConfigurationCompletedWithErrors {
            get {
                return ResourceManager.GetString("ConfigurationCompletedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None — skip.
        /// </summary>
        internal static string SkipNoneDescription {
            get {
                return ResourceManager.GetString("SkipNoneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to configure?.
        /// </summary>
        internal static string InitCommand_WhatToConfigure {
            get {
                return ResourceManager.GetString("InitCommand_WhatToConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No options selected. Nothing to configure..
        /// </summary>
        internal static string InitCommand_NothingSelected {
            get {
                return ResourceManager.GetString("InitCommand_NothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Aspire MCP server.
        /// </summary>
        internal static string InitCommand_ConfigureMcpServer {
            get {
                return ResourceManager.GetString("InitCommand_ConfigureMcpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Aspire skill file (Recommended).
        /// </summary>
        internal static string InitCommand_InstallSkillFile {
            get {
                return ResourceManager.GetString("InitCommand_InstallSkillFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Where should skill files be installed?.
        /// </summary>
        internal static string InitCommand_SelectSkillLocations {
            get {
                return ResourceManager.GetString("InitCommand_SelectSkillLocations", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Which skills should be installed?.
        /// </summary>
        internal static string InitCommand_SelectSkills {
            get {
                return ResourceManager.GetString("InitCommand_SelectSkills", resourceCulture);
            }
        }
    }
}
