//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DoCommandStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DoCommandStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.DoCommandStrings", typeof(DoCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute a specific pipeline step and its dependencies. (Preview).
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing pipeline....
        /// </summary>
        public static string GeneratingArtifacts {
            get {
                return ResourceManager.GetString("GeneratingArtifacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was canceled..
        /// </summary>
        public static string OperationCanceled {
            get {
                return ResourceManager.GetString("OperationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPERATION COMPLETED.
        /// </summary>
        public static string OperationCompletedPrefix {
            get {
                return ResourceManager.GetString("OperationCompletedPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPERATION FAILED.
        /// </summary>
        public static string OperationFailedPrefix {
            get {
                return ResourceManager.GetString("OperationFailedPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The optional output path for artifacts..
        /// </summary>
        public static string OutputPathArgumentDescription {
            get {
                return ResourceManager.GetString("OutputPathArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the step to execute..
        /// </summary>
        public static string StepArgumentDescription {
            get {
                return ResourceManager.GetString("StepArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the pipeline step to execute.
        /// </summary>
        public static string PromptForStep {
            get {
                return ResourceManager.GetString("PromptForStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step name is required..
        /// </summary>
        public static string StepRequired {
            get {
                return ResourceManager.GetString("StepRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the environment.
        /// </summary>
        public static string PromptForEnvironment {
            get {
                return ResourceManager.GetString("PromptForEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom....
        /// </summary>
        public static string CustomEnvironmentOption {
            get {
                return ResourceManager.GetString("CustomEnvironmentOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter custom environment name.
        /// </summary>
        public static string PromptForCustomEnvironment {
            get {
                return ResourceManager.GetString("PromptForCustomEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify output path for artifacts?.
        /// </summary>
        public static string PromptForOutputPathConfirm {
            get {
                return ResourceManager.GetString("PromptForOutputPathConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter output path.
        /// </summary>
        public static string PromptForOutputPath {
            get {
                return ResourceManager.GetString("PromptForOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify log level?.
        /// </summary>
        public static string PromptForLogLevelConfirm {
            get {
                return ResourceManager.GetString("PromptForLogLevelConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select log level.
        /// </summary>
        public static string PromptForLogLevel {
            get {
                return ResourceManager.GetString("PromptForLogLevel", resourceCulture);
            }
        }
    }
}
