//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DocsCommandStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocsCommandStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.DocsCommandStrings", typeof(DocsCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse and search Aspire documentation from aspire.dev..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all available Aspire documentation pages..
        /// </summary>
        internal static string ListDescription {
            get {
                return ResourceManager.GetString("ListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Aspire documentation by keywords..
        /// </summary>
        internal static string SearchDescription {
            get {
                return ResourceManager.GetString("SearchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the full content of a documentation page by its slug..
        /// </summary>
        internal static string GetDescription {
            get {
                return ResourceManager.GetString("GetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search query..
        /// </summary>
        internal static string QueryArgumentDescription {
            get {
                return ResourceManager.GetString("QueryArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The slug of the documentation page (e.g., 'redis-integration')..
        /// </summary>
        internal static string SlugArgumentDescription {
            get {
                return ResourceManager.GetString("SlugArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output format (Table or Json)..
        /// </summary>
        internal static string FormatOptionDescription {
            get {
                return ResourceManager.GetString("FormatOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of search results to return (default: 5, max: 10)..
        /// </summary>
        internal static string LimitOptionDescription {
            get {
                return ResourceManager.GetString("LimitOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return only the specified section of the page..
        /// </summary>
        internal static string SectionOptionDescription {
            get {
                return ResourceManager.GetString("SectionOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading documentation....
        /// </summary>
        internal static string LoadingDocumentation {
            get {
                return ResourceManager.GetString("LoadingDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No documentation available. The aspire.dev docs may not have loaded correctly..
        /// </summary>
        internal static string NoDocumentationAvailable {
            get {
                return ResourceManager.GetString("NoDocumentationAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found for '{0}'. Try different search terms..
        /// </summary>
        internal static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation page '{0}' not found. Use 'aspire docs list' to see available pages..
        /// </summary>
        internal static string DocumentNotFound {
            get {
                return ResourceManager.GetString("DocumentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} documentation pages..
        /// </summary>
        internal static string FoundDocumentationPages {
            get {
                return ResourceManager.GetString("FoundDocumentationPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} results for '{1}'..
        /// </summary>
        internal static string FoundSearchResults {
            get {
                return ResourceManager.GetString("FoundSearchResults", resourceCulture);
            }
        }
    }
}
