//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Cli.Resources.ErrorStrings", typeof(ErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already connected to AppHost backchannel..
        /// </summary>
        public static string AlreadyConnectedToBackchannel {
            get {
                return ResourceManager.GetString("AlreadyConnectedToBackchannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppHost is incompatible with the CLI. The AppHost must be updated to a version that supports the {0} capability..
        /// </summary>
        public static string AppHostIncompatibleWithCli {
            get {
                return ResourceManager.GetString("AppHostIncompatibleWithCli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppHost file was specified in &apos;{0}&apos; but it does not exist at &apos;{1}&apos;..
        /// </summary>
        public static string AppHostWasSpecifiedButDoesntExist {
            get {
                return ResourceManager.GetString("AppHostWasSpecifiedButDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AspireHostingVersion is null.
        /// </summary>
        public static string AspireHostingVersionNull {
            get {
                return ResourceManager.GetString("AspireHostingVersionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Aspire.Hosting package version {0} is not supported. Please update to the latest version..
        /// </summary>
        public static string AspireSDKVersionNotSupported {
            get {
                return ResourceManager.GetString("AspireSDKVersionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use --watch and --no-build at the same time..
        /// </summary>
        public static string CantUseBothWatchAndNoBuild {
            get {
                return ResourceManager.GetString("CantUseBothWatchAndNoBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer certificates may not be fully trusted (trust exit code was: {0})..
        /// </summary>
        public static string CertificatesMayNotBeFullyTrusted {
            get {
                return ResourceManager.GetString("CertificatesMayNotBeFullyTrusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration key {0} not found..
        /// </summary>
        public static string ConfigurationKeyNotFound {
            get {
                return ResourceManager.GetString("ConfigurationKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration key is required..
        /// </summary>
        public static string ConfigurationKeyRequired {
            get {
                return ResourceManager.GetString("ConfigurationKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration value is required..
        /// </summary>
        public static string ConfigurationValueRequired {
            get {
                return ResourceManager.GetString("ConfigurationValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse Aspire.Hosting package version..
        /// </summary>
        public static string CouldNotParseAspireSDKVersion {
            get {
                return ResourceManager.GetString("CouldNotParseAspireSDKVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting configuration: {0}.
        /// </summary>
        public static string ErrorDeletingConfiguration {
            get {
                return ResourceManager.GetString("ErrorDeletingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting configuration: {0}.
        /// </summary>
        public static string ErrorSettingConfiguration {
            get {
                return ResourceManager.GetString("ErrorSettingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse template version from stdout..
        /// </summary>
        public static string FailedToParseTemplateVersionFromStdout {
            get {
                return ResourceManager.GetString("FailedToParseTemplateVersionFromStdout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve template packages via cache..
        /// </summary>
        public static string FailedToRetrieveCachedTemplatePackages {
            get {
                return ResourceManager.GetString("FailedToRetrieveCachedTemplatePackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to search for packages. Exit code: {0}..
        /// </summary>
        public static string FailedToSearchForPackages {
            get {
                return ResourceManager.GetString("FailedToSearchForPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid locale {0} provided will not be used..
        /// </summary>
        public static string InvalidLocaleProvided {
            get {
                return ResourceManager.GetString("InvalidLocaleProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple project files found..
        /// </summary>
        public static string MultipleProjectFilesFound {
            get {
                return ResourceManager.GetString("MultipleProjectFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project file found..
        /// </summary>
        public static string NoProjectFileFound {
            get {
                return ResourceManager.GetString("NoProjectFileFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project could not be analyzed due to a build error. For more information run with --debug switch..
        /// </summary>
        public static string ProjectCouldNotBeAnalyzed {
            get {
                return ResourceManager.GetString("ProjectCouldNotBeAnalyzed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project file does not exist..
        /// </summary>
        public static string ProjectFileDoesntExist {
            get {
                return ResourceManager.GetString("ProjectFileDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project file is not an Aspire app host project..
        /// </summary>
        public static string ProjectFileNotAppHostProject {
            get {
                return ResourceManager.GetString("ProjectFileNotAppHostProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project is not an Aspire app host project..
        /// </summary>
        public static string ProjectIsNotAppHost {
            get {
                return ResourceManager.GetString("ProjectIsNotAppHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the assembly version..
        /// </summary>
        public static string UnableToRetrieveAssemblyVersion {
            get {
                return ResourceManager.GetString("UnableToRetrieveAssemblyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported locale {0} provided will not be used. Supported locales are: {1}..
        /// </summary>
        public static string UnsupportedLocaleProvided {
            get {
                return ResourceManager.GetString("UnsupportedLocaleProvided", resourceCulture);
            }
        }
    }
}
