//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InitCommandStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InitCommandStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Aspire.Cli.Resources.InitCommandStrings", typeof(InitCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string SolutionDetected {
            get {
                return ResourceManager.GetString("SolutionDetected", resourceCulture);
            }
        }
        
        internal static string CreatingAppHostProject {
            get {
                return ResourceManager.GetString("CreatingAppHostProject", resourceCulture);
            }
        }
        
        internal static string CreatingServiceDefaultsProject {
            get {
                return ResourceManager.GetString("CreatingServiceDefaultsProject", resourceCulture);
            }
        }
        
        internal static string AddingProjectsToSolution {
            get {
                return ResourceManager.GetString("AddingProjectsToSolution", resourceCulture);
            }
        }
        
        internal static string NoSolutionFoundCreatingSingleFileAppHost {
            get {
                return ResourceManager.GetString("NoSolutionFoundCreatingSingleFileAppHost", resourceCulture);
            }
        }
        
        internal static string AspireInitializationComplete {
            get {
                return ResourceManager.GetString("AspireInitializationComplete", resourceCulture);
            }
        }
        
        internal static string MultipleSolutionsFound {
            get {
                return ResourceManager.GetString("MultipleSolutionsFound", resourceCulture);
            }
        }
        
        internal static string SolutionAlreadyInitialized {
            get {
                return ResourceManager.GetString("SolutionAlreadyInitialized", resourceCulture);
            }
        }
        
        internal static string AddingAppHostProjectToSolution {
            get {
                return ResourceManager.GetString("AddingAppHostProjectToSolution", resourceCulture);
            }
        }
        
        internal static string AddingServiceDefaultsProjectToSolution {
            get {
                return ResourceManager.GetString("AddingServiceDefaultsProjectToSolution", resourceCulture);
            }
        }
    }
}