//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogCommandStrings {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogCommandStrings() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Aspire.Cli.Resources.LogCommandStrings", typeof(LogCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        public static string ResourceArgumentDescription {
            get {
                return ResourceManager.GetString("ResourceArgumentDescription", resourceCulture);
            }
        }

        public static string LinesArgumentDescription {
            get {
                return ResourceManager.GetString("LinesArgumentDescription", resourceCulture);
            }
        }

        public static string TailArgumentDescription {
            get {
                return ResourceManager.GetString("TailArgumentDescription", resourceCulture);
            }
        }

        public static string ProjectArgumentDescription {
            get {
                return ResourceManager.GetString("ProjectArgumentDescription", resourceCulture);
            }
        }

        public static string ResourceNameRequired {
            get {
                return ResourceManager.GetString("ResourceNameRequired", resourceCulture);
            }
        }

        public static string NoRunningAppHost {
            get {
                return ResourceManager.GetString("NoRunningAppHost", resourceCulture);
            }
        }

        public static string TailingLogs {
            get {
                return ResourceManager.GetString("TailingLogs", resourceCulture);
            }
        }

        public static string ShowingRecentLogs {
            get {
                return ResourceManager.GetString("ShowingRecentLogs", resourceCulture);
            }
        }

        public static string FailedToGetLogs {
            get {
                return ResourceManager.GetString("FailedToGetLogs", resourceCulture);
            }
        }
    }
}