//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class McpCommandStrings {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal McpCommandStrings() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Aspire.Cli.Resources.McpCommandStrings", typeof(McpCommandStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        internal static string StartCommand_Description {
            get {
                return ResourceManager.GetString("StartCommand_Description", resourceCulture);
            }
        }

        internal static string InitCommand_Description {
            get {
                return ResourceManager.GetString("InitCommand_Description", resourceCulture);
            }
        }

        internal static string DeprecatedCommandWarning {
            get {
                return ResourceManager.GetString("DeprecatedCommandWarning", resourceCulture);
            }
        }

        internal static string InitCommand_NoAgentEnvironmentsDetected {
            get {
                return ResourceManager.GetString("InitCommand_NoAgentEnvironmentsDetected", resourceCulture);
            }
        }

        internal static string InitCommand_ConfigurationComplete {
            get {
                return ResourceManager.GetString("InitCommand_ConfigurationComplete", resourceCulture);
            }
        }

        internal static string InitCommand_DetectingAgentEnvironments {
            get {
                return ResourceManager.GetString("InitCommand_DetectingAgentEnvironments", resourceCulture);
            }
        }

        internal static string InitCommand_WorkspaceRootPrompt {
            get {
                return ResourceManager.GetString("InitCommand_WorkspaceRootPrompt", resourceCulture);
            }
        }

        internal static string InitCommand_WorkspaceRootRequired {
            get {
                return ResourceManager.GetString("InitCommand_WorkspaceRootRequired", resourceCulture);
            }
        }

        internal static string InitCommand_WorkspaceRootNotFound {
            get {
                return ResourceManager.GetString("InitCommand_WorkspaceRootNotFound", resourceCulture);
            }
        }

        internal static string InvalidJsonInputExpectedObject {
            get {
                return ResourceManager.GetString("InvalidJsonInputExpectedObject", resourceCulture);
            }
        }

        internal static string InvalidJsonInput {
            get {
                return ResourceManager.GetString("InvalidJsonInput", resourceCulture);
            }
        }

        internal static string FailedToCallTool {
            get {
                return ResourceManager.GetString("FailedToCallTool", resourceCulture);
            }
        }

        internal static string NoResourcesWithMcpTools {
            get {
                return ResourceManager.GetString("NoResourcesWithMcpTools", resourceCulture);
            }
        }
    }
}
