//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Cli.Resources {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TemplatingStrings {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TemplatingStrings() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Aspire.Cli.Resources.TemplatingStrings", typeof(TemplatingStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string AtLeastOneTemplateFactoryMustBeProvided {
            get {
                return ResourceManager.GetString("AtLeastOneTemplateFactoryMustBeProvided", resourceCulture);
            }
        }

        public static string AspireStarter_Description {
            get {
                return ResourceManager.GetString("AspireStarter_Description", resourceCulture);
            }
        }

        public static string AspireJsFrontendStarter_Description {
            get {
                return ResourceManager.GetString("AspireJsFrontendStarter_Description", resourceCulture);
            }
        }

        public static string AspireEmpty_Description {
            get {
                return ResourceManager.GetString("AspireEmpty_Description", resourceCulture);
            }
        }

        public static string AspireAppHost_Description {
            get {
                return ResourceManager.GetString("AspireAppHost_Description", resourceCulture);
            }
        }

        public static string AspireServiceDefaults_Description {
            get {
                return ResourceManager.GetString("AspireServiceDefaults_Description", resourceCulture);
            }
        }

        public static string AspirePyStarter_Description {
            get {
                return ResourceManager.GetString("AspirePyStarter_Description", resourceCulture);
            }
        }

        public static string AspireAppHostSingleFile_Description {
            get {
                return ResourceManager.GetString("AspireAppHostSingleFile_Description", resourceCulture);
            }
        }

        public static string AspireMSTest_Description {
            get {
                return ResourceManager.GetString("AspireMSTest_Description", resourceCulture);
            }
        }

        public static string AspireNUnit_Description {
            get {
                return ResourceManager.GetString("AspireNUnit_Description", resourceCulture);
            }
        }

        public static string AspireXUnit_Description {
            get {
                return ResourceManager.GetString("AspireXUnit_Description", resourceCulture);
            }
        }

        public static string IntegrationTestsTemplate_Description {
            get {
                return ResourceManager.GetString("IntegrationTestsTemplate_Description", resourceCulture);
            }
        }

        public static string UseRedisCache_Prompt {
            get {
                return ResourceManager.GetString("UseRedisCache_Prompt", resourceCulture);
            }
        }

        public static string UseRedisCache_Description {
            get {
                return ResourceManager.GetString("UseRedisCache_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Redis Cache for caching..
        /// </summary>
        public static string UseRedisCache_UsingRedisCache {
            get {
                return ResourceManager.GetString("UseRedisCache_UsingRedisCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using project templates version: {0}.
        /// </summary>
        public static string UsingProjectTemplatesVersion {
            get {
                return ResourceManager.GetString("UsingProjectTemplatesVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run 'cd "{0}"' and then 'aspire run' to start your AppHost..
        /// </summary>
        public static string RunCdThenAspireRun {
            get {
                return ResourceManager.GetString("RunCdThenAspireRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run 'aspire run' to start your AppHost..
        /// </summary>
        public static string RunAspireRun {
            get {
                return ResourceManager.GetString("RunAspireRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        public static string UseRedisCache_UnexpectedChoice {
            get {
                return ResourceManager.GetString("UseRedisCache_UnexpectedChoice", resourceCulture);
            }
        }

        public static string PromptForTFMOptions_Prompt {
            get {
                return ResourceManager.GetString("PromptForTFMOptions_Prompt", resourceCulture);
            }
        }

        public static string PromptForTFMOptions_Description {
            get {
                return ResourceManager.GetString("PromptForTFMOptions_Description", resourceCulture);
            }
        }

        public static string PromptForTFM_Prompt {
            get {
                return ResourceManager.GetString("PromptForTFM_Prompt", resourceCulture);
            }
        }

        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }

        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }

        public static string PromptForTFM_UsingForTesting {
            get {
                return ResourceManager.GetString("PromptForTFM_UsingForTesting", resourceCulture);
            }
        }

        public static string EnterXUnitVersion_Prompt {
            get {
                return ResourceManager.GetString("EnterXUnitVersion_Prompt", resourceCulture);
            }
        }

        public static string EnterXUnitVersion_Description {
            get {
                return ResourceManager.GetString("EnterXUnitVersion_Description", resourceCulture);
            }
        }

        public static string GettingTemplates {
            get {
                return ResourceManager.GetString("GettingTemplates", resourceCulture);
            }
        }

        public static string TemplateInstallationFailed {
            get {
                return ResourceManager.GetString("TemplateInstallationFailed", resourceCulture);
            }
        }

        public static string CreatingNewProject {
            get {
                return ResourceManager.GetString("CreatingNewProject", resourceCulture);
            }
        }

        public static string ProjectCreationFailed {
            get {
                return ResourceManager.GetString("ProjectCreationFailed", resourceCulture);
            }
        }

        public static string ProjectCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ProjectCreatedSuccessfully", resourceCulture);
            }
        }

        public static string CertificateTrustError {
            get {
                return ResourceManager.GetString("CertificateTrustError", resourceCulture);
            }
        }

        public static string SearchingForAvailableTemplateVersions {
            get {
                return ResourceManager.GetString("SearchingForAvailableTemplateVersions", resourceCulture);
            }
        }

        public static string NoTemplateVersionsFound {
            get {
                return ResourceManager.GetString("NoTemplateVersionsFound", resourceCulture);
            }
        }

        public static string ProjectAlreadyExists {
            get {
                return ResourceManager.GetString("ProjectAlreadyExists", resourceCulture);
            }
        }

        public static string CreateNugetConfigConfirmation {
            get {
                return ResourceManager.GetString("CreateNugetConfigConfirmation", resourceCulture);
            }
        }

        public static string NuGetConfigCreatedConfirmationMessage {
            get {
                return ResourceManager.GetString("NuGetConfigCreatedConfirmationMessage", resourceCulture);
            }
        }

        public static string UseLocalhostTld_Prompt {
            get {
                return ResourceManager.GetString("UseLocalhostTld_Prompt", resourceCulture);
            }
        }

        public static string UseLocalhostTld_UnexpectedChoice {
            get {
                return ResourceManager.GetString("UseLocalhostTld_UnexpectedChoice", resourceCulture);
            }
        }

        public static string UseLocalhostTld_UsingLocalhostTld {
            get {
                return ResourceManager.GetString("UseLocalhostTld_UsingLocalhostTld", resourceCulture);
            }
        }

        public static string UseLocalhostTld_Description {
            get {
                return ResourceManager.GetString("UseLocalhostTld_Description", resourceCulture);
            }
        }

        internal static string LanguageSelectionRequired {
            get {
                return ResourceManager.GetString("LanguageSelectionRequired", resourceCulture);
            }
        }

        internal static string UnableToDetermineAspireVersionForTypeScript {
            get {
                return ResourceManager.GetString("UnableToDetermineAspireVersionForTypeScript", resourceCulture);
            }
        }

        internal static string UnknownLanguageId {
            get {
                return ResourceManager.GetString("UnknownLanguageId", resourceCulture);
            }
        }

        internal static string FailedToCreateProjectFiles {
            get {
                return ResourceManager.GetString("FailedToCreateProjectFiles", resourceCulture);
            }
        }

        internal static string UpdateNuGetConfigPrompt {
            get {
                return ResourceManager.GetString("UpdateNuGetConfigPrompt", resourceCulture);
            }
        }

        internal static string UpdatedNuGetConfigMessage {
            get {
                return ResourceManager.GetString("UpdatedNuGetConfigMessage", resourceCulture);
            }
        }

        internal static string CreatedOrUpdatedNuGetConfigMessage {
            get {
                return ResourceManager.GetString("CreatedOrUpdatedNuGetConfigMessage", resourceCulture);
            }
        }
    }
}
