//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Hosting.Azure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AzureProvisioningStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AzureProvisioningStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Hosting.Azure.Resources.AzureProvisioningStrings", typeof(AzureProvisioningStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model contains Azure resources that require an Azure Subscription.
        ///
        ///To learn more, see the [Azure provisioning docs](https://aka.ms/dotnet/aspire/azure/provisioning)..
        /// </summary>
        internal static string InputsMessage {
            get {
                return ResourceManager.GetString("InputsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure provisioning.
        /// </summary>
        internal static string InputsTitle {
            get {
                return ResourceManager.GetString("InputsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select location.
        /// </summary>
        internal static string LocationPlaceholder {
            get {
                return ResourceManager.GetString("LocationPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model contains Azure resources that require an Azure Subscription..
        /// </summary>
        internal static string NotificationMessage {
            get {
                return ResourceManager.GetString("NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter values.
        /// </summary>
        internal static string NotificationPrimaryButtonText {
            get {
                return ResourceManager.GetString("NotificationPrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure provisioning.
        /// </summary>
        internal static string NotificationTitle {
            get {
                return ResourceManager.GetString("NotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource group.
        /// </summary>
        internal static string ResourceGroupLabel {
            get {
                return ResourceManager.GetString("ResourceGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription ID.
        /// </summary>
        internal static string SubscriptionIdLabel {
            get {
                return ResourceManager.GetString("SubscriptionIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select subscription ID.
        /// </summary>
        internal static string SubscriptionIdPlaceholder {
            get {
                return ResourceManager.GetString("SubscriptionIdPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource group name must be a valid Azure resource group name..
        /// </summary>
        internal static string ValidationResourceGroupNameInvalid {
            get {
                return ResourceManager.GetString("ValidationResourceGroupNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription ID must be a valid GUID..
        /// </summary>
        internal static string ValidationSubscriptionIdInvalid {
            get {
                return ResourceManager.GetString("ValidationSubscriptionIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure subscription.
        /// </summary>
        internal static string SubscriptionDialogTitle {
            get {
                return ResourceManager.GetString("SubscriptionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your Azure subscription:.
        /// </summary>
        internal static string SubscriptionSelectionMessage {
            get {
                return ResourceManager.GetString("SubscriptionSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Azure subscription ID:.
        /// </summary>
        internal static string SubscriptionManualEntryMessage {
            get {
                return ResourceManager.GetString("SubscriptionManualEntryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure location and resource group.
        /// </summary>
        internal static string LocationDialogTitle {
            get {
                return ResourceManager.GetString("LocationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your Azure location and specify resource group:.
        /// </summary>
        internal static string LocationSelectionMessage {
            get {
                return ResourceManager.GetString("LocationSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure tenant.
        /// </summary>
        internal static string TenantDialogTitle {
            get {
                return ResourceManager.GetString("TenantDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your Azure tenant:.
        /// </summary>
        internal static string TenantSelectionMessage {
            get {
                return ResourceManager.GetString("TenantSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Azure tenant ID:.
        /// </summary>
        internal static string TenantManualEntryMessage {
            get {
                return ResourceManager.GetString("TenantManualEntryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant ID.
        /// </summary>
        internal static string TenantLabel {
            get {
                return ResourceManager.GetString("TenantLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tenant ID.
        /// </summary>
        internal static string TenantPlaceholder {
            get {
                return ResourceManager.GetString("TenantPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant ID must be a valid GUID.
        /// </summary>
        internal static string ValidationTenantIdInvalid {
            get {
                return ResourceManager.GetString("ValidationTenantIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or enter resource group.
        /// </summary>
        internal static string ResourceGroupPlaceholder {
            get {
                return ResourceManager.GetString("ResourceGroupPlaceholder", resourceCulture);
            }
        }
    }
}