//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting.RemoteHost
{
    public static partial class RemoteHostServer
    {
        public static System.Threading.Tasks.Task RunAsync(string[] args) { throw null; }
    }
}