@HostAddress = https://localhost:7060

GET {{HostAddress}}/ping/

###

POST {{HostAddress}}/stream/
Content-Type: application/json

{
  "name": "EVENTS",
  "description": "Events Description",
  "subjects": ["events.>"],
  "max_msgs": 10
}

###

GET {{HostAddress}}/stream/EVENTS
Accept: application/json

###

POST {{HostAddress}}/publish/
Content-Type: application/json

{
  "subject": "events.mouse.click",
  "name": "Mouse Event",
  "description": "Mouse Event Description",
  "priority": 0.1
}

###

POST {{HostAddress}}/publish/
Content-Type: application/json

{
  "subject": "events.key.a",
  "name": "Key Event",
  "description": "Key Event Description",
  "priority": 0.5
}

###

GET {{HostAddress}}/consume/EVENTS
Accept: application/json

###
