// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace Aspire.Cli.Embedded;

[GenerateFileAccessor]
[EmbedFile("Shared/RemoteAppHost/InstructionModels.cs", nameof(InstructionModels))]
[EmbedFile("Shared/RemoteAppHost/InstructionProcessor.cs", nameof(InstructionProcessor))]
[EmbedFile("Shared/RemoteAppHost/JsonRpcServer.cs", nameof(JsonRpcServer))]
[EmbedFile("Shared/RemoteAppHost/OrphanDetector.cs", nameof(OrphanDetector))]
[EmbedFile("Shared/RemoteAppHost/Program.cs", nameof(ProgramCs))]
[EmbedFile("Shared/python/remote_app_host_client.py", nameof(RemoteAppHostClientPy))]
[EmbedFile("Shared/typescript/package.json", nameof(TsPackageJson))]
[EmbedFile("Shared/typescript/RemoteAppHostClient.ts", nameof(RemoteAppHostClientTs))]
[EmbedFile("Shared/typescript/types.ts", nameof(TypesTs))]
internal static partial class EmbeddedFiles
{
    // Properties generated by source generator
}
