---
name: 'Build CLI archives'
description: 'Build CLI archives'
inputs:
  targetRids:
    description: ':-separated list of target RIDs'
    required: true
    type: string
    default: ''
  extraBuildArgs:
    required: false
    type: string
    default: ''

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@3951f0dfe7a07e2313ec93c75700083e2005cbab # v4.3.0
      with:
        global-json-file: global.json

    - name: Setup vars (Linux)
      shell: pwsh
      if: ${{ inputs.os == 'ubuntu-latest' || inputs.os == 'macos-latest' }}
      run: |
        echo "DOTNET_SCRIPT=./dotnet.sh" >> $GITHUB_ENV
        echo "BUILD_SCRIPT=./build.sh" >> $GITHUB_ENV
        echo ${{ github.workspace }}/.dotnet >> $GITHUB_PATH

    - name: Setup vars (Windows)
      shell: bash
      if: ${{ inputs.os == 'windows-latest' }}
      run: |
        echo "DOTNET_SCRIPT=.\dotnet.cmd" >> $env:GITHUB_ENV
        echo "BUILD_SCRIPT=.\build.cmd" >> $env:GITHUB_ENV
        echo ${{ github.workspace }}\.dotnet >> $env:GITHUB_PATH

    - name: Build CLI packages
      env:
        CI: false
      shell: pwsh
      run: >
        ./eng/build.ps1
        --ci
        --build
        --restore
        -bl:${{ github.workspace }}/artifacts/log/Debug/BuildCli.binlog
        /p:ContinuousIntegrationBuild=true
        /p:SkipManagedBuild=true
        /p:TargetRids=${{ inputs.TargetRids }}
        ${{ inputs.extraBuildArgs }}

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1  # v4.6.1
      with:
        name: build-cli-logs
        path: artifacts/log/**

    - name: Upload CLI archives
      if: always()
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1  # v4.6.1
      with:
        name: build-cli-archives-${{ join('_', inputs.targetRids) }}
        path: artifacts/packages
