//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Dashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AIPrompts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AIPrompts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Dashboard.Resources.AIPrompts", typeof(AIPrompts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze log entry `log_id: {0}`.
        /// </summary>
        public static string PromptAnalyzeLogEntry {
            get {
                return ResourceManager.GetString("PromptAnalyzeLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze performance.
        /// </summary>
        public static string PromptAnalyzePerformance {
            get {
                return ResourceManager.GetString("PromptAnalyzePerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze resource `{0}`.
        /// </summary>
        public static string PromptAnalyzeResource {
            get {
                return ResourceManager.GetString("PromptAnalyzeResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze performance for `{0}`.
        /// </summary>
        public static string PromptAnalyzeResourcePerformance {
            get {
                return ResourceManager.GetString("PromptAnalyzeResourcePerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explain the current state of my app&apos;s resources.
        /// </summary>
        public static string PromptAnalyzeResources {
            get {
                return ResourceManager.GetString("PromptAnalyzeResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze span `{0}`.
        /// </summary>
        public static string PromptAnalyzeSpan {
            get {
                return ResourceManager.GetString("PromptAnalyzeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get structured logs for all resources.
        /// </summary>
        public static string PromptAnalyzeStructuredLogs {
            get {
                return ResourceManager.GetString("PromptAnalyzeStructuredLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze distributed trace `trace_id: {0}`.
        /// </summary>
        public static string PromptAnalyzeTrace {
            get {
                return ResourceManager.GetString("PromptAnalyzeTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get console logs for all resources.
        /// </summary>
        public static string PromptConsoleLogs {
            get {
                return ResourceManager.GetString("PromptConsoleLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze structured log errors.
        /// </summary>
        public static string PromptErrorsStructuredLogs {
            get {
                return ResourceManager.GetString("PromptErrorsStructuredLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze distributed trace errors.
        /// </summary>
        public static string PromptErrorTraces {
            get {
                return ResourceManager.GetString("PromptErrorTraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe using console logs.
        /// </summary>
        public static string PromptHelpConsoleLogs {
            get {
                return ResourceManager.GetString("PromptHelpConsoleLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe using resources.
        /// </summary>
        public static string PromptHelpResources {
            get {
                return ResourceManager.GetString("PromptHelpResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe using structured logs.
        /// </summary>
        public static string PromptHelpStructuredLogs {
            get {
                return ResourceManager.GetString("PromptHelpStructuredLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe using distributed traces.
        /// </summary>
        public static string PromptHelpTraces {
            get {
                return ResourceManager.GetString("PromptHelpTraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get console logs for `{0}`.
        /// </summary>
        public static string PromptResourceConsoleLogs {
            get {
                return ResourceManager.GetString("PromptResourceConsoleLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get structured logs for `{0}`.
        /// </summary>
        public static string PromptResourceStructuredLogs {
            get {
                return ResourceManager.GetString("PromptResourceStructuredLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get distributed traces for `{0}`.
        /// </summary>
        public static string PromptResourceTraces {
            get {
                return ResourceManager.GetString("PromptResourceTraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get traces and structured logs for `{0}`.
        /// </summary>
        public static string PromptResourceTracesAndStructuredLogs {
            get {
                return ResourceManager.GetString("PromptResourceTracesAndStructuredLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get distributed traces for all resources.
        /// </summary>
        public static string PromptTraces {
            get {
                return ResourceManager.GetString("PromptTraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get traces and structured logs.
        /// </summary>
        public static string PromptTracesAndStructuredLogs {
            get {
                return ResourceManager.GetString("PromptTracesAndStructuredLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that all resources are in a healthy state.
        /// </summary>
        public static string PromptUnhealthyResources {
            get {
                return ResourceManager.GetString("PromptUnhealthyResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explain errors.
        /// </summary>
        public static string TitleExplainErrors {
            get {
                return ResourceManager.GetString("TitleExplainErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string TitleHelp {
            get {
                return ResourceManager.GetString("TitleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigate.
        /// </summary>
        public static string TitleInvestigate {
            get {
                return ResourceManager.GetString("TitleInvestigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigate unhealthy resources.
        /// </summary>
        public static string TitleInvestigateUnhealthyResources {
            get {
                return ResourceManager.GetString("TitleInvestigateUnhealthyResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string TitlePerformance {
            get {
                return ResourceManager.GetString("TitlePerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent activity.
        /// </summary>
        public static string TitleRecentActivity {
            get {
                return ResourceManager.GetString("TitleRecentActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent console logs.
        /// </summary>
        public static string TitleRecentConsoleLogs {
            get {
                return ResourceManager.GetString("TitleRecentConsoleLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summarize resources.
        /// </summary>
        public static string TitleSummarizeResources {
            get {
                return ResourceManager.GetString("TitleSummarizeResources", resourceCulture);
            }
        }
    }
}
