//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Dashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConsoleLogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleLogs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Dashboard.Resources.ConsoleLogs", typeof(ConsoleLogs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error watching logs.
        /// </summary>
        public static string ConsoleLogsErrorWatchingLogs {
            get {
                return ResourceManager.GetString("ConsoleLogsErrorWatchingLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished watching logs.
        /// </summary>
        public static string ConsoleLogsFinishedWatchingLogs {
            get {
                return ResourceManager.GetString("ConsoleLogsFinishedWatchingLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console logs.
        /// </summary>
        public static string ConsoleLogsHeader {
            get {
                return ResourceManager.GetString("ConsoleLogsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading resources ....
        /// </summary>
        public static string ConsoleLogsLoadingResources {
            get {
                return ResourceManager.GetString("ConsoleLogsLoadingResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs not yet available.
        /// </summary>
        public static string ConsoleLogsLogsNotYetAvailable {
            get {
                return ResourceManager.GetString("ConsoleLogsLogsNotYetAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No resource selected.
        /// </summary>
        public static string ConsoleLogsNoResourceSelected {
            get {
                return ResourceManager.GetString("ConsoleLogsNoResourceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No wrap log lines.
        /// </summary>
        public static string ConsoleLogsNoWrapLogs {
            get {
                return ResourceManager.GetString("ConsoleLogsNoWrapLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} console logs.
        /// </summary>
        public static string ConsoleLogsPageTitle {
            get {
                return ResourceManager.GetString("ConsoleLogsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Log capture paused at {0}, {1} log(s) filtered out&gt;.
        /// </summary>
        public static string ConsoleLogsPauseActive {
            get {
                return ResourceManager.GetString("ConsoleLogsPauseActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Log capture paused between {0} and {1}, {2} log(s) filtered out&gt;.
        /// </summary>
        public static string ConsoleLogsPauseDetails {
            get {
                return ResourceManager.GetString("ConsoleLogsPauseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource actions.
        /// </summary>
        public static string ConsoleLogsResourceActions {
            get {
                return ResourceManager.GetString("ConsoleLogsResourceActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select resource.
        /// </summary>
        public static string ConsoleLogsSelectResourceToolbar {
            get {
                return ResourceManager.GetString("ConsoleLogsSelectResourceToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console logs settings.
        /// </summary>
        public static string ConsoleLogsSettings {
            get {
                return ResourceManager.GetString("ConsoleLogsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide timestamps.
        /// </summary>
        public static string ConsoleLogsTimestampHide {
            get {
                return ResourceManager.GetString("ConsoleLogsTimestampHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show timestamps.
        /// </summary>
        public static string ConsoleLogsTimestampShow {
            get {
                return ResourceManager.GetString("ConsoleLogsTimestampShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTC timestamps.
        /// </summary>
        public static string ConsoleLogsTimestampShowUtc {
            get {
                return ResourceManager.GetString("ConsoleLogsTimestampShowUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown state.
        /// </summary>
        public static string ConsoleLogsUnknownState {
            get {
                return ResourceManager.GetString("ConsoleLogsUnknownState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching logs....
        /// </summary>
        public static string ConsoleLogsWatchingLogs {
            get {
                return ResourceManager.GetString("ConsoleLogsWatchingLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap log lines.
        /// </summary>
        public static string ConsoleLogsWrapLogs {
            get {
                return ResourceManager.GetString("ConsoleLogsWrapLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download logs.
        /// </summary>
        public static string DownloadLogs {
            get {
                return ResourceManager.GetString("DownloadLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service log status.
        /// </summary>
        public static string LogStatusLabel {
            get {
                return ResourceManager.GetString("LogStatusLabel", resourceCulture);
            }
        }
    }
}
