//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Dashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConsoleLogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleLogs() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Dashboard.Resources.ConsoleLogs", typeof(ConsoleLogs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to initialize.
        /// </summary>
        public static string ConsoleLogsFailedToInitialize {
            get {
                return ResourceManager.GetString("ConsoleLogsFailedToInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finished watching logs.
        /// </summary>
        public static string ConsoleLogsFinishedWatchingLogs {
            get {
                return ResourceManager.GetString("ConsoleLogsFinishedWatchingLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Console Logs.
        /// </summary>
        public static string ConsoleLogsHeader {
            get {
                return ResourceManager.GetString("ConsoleLogsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initializing log viewer....
        /// </summary>
        public static string ConsoleLogsInitializingLogViewer {
            get {
                return ResourceManager.GetString("ConsoleLogsInitializingLogViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading resources ....
        /// </summary>
        public static string ConsoleLogsLoadingResources {
            get {
                return ResourceManager.GetString("ConsoleLogsLoadingResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs not yet available.
        /// </summary>
        public static string ConsoleLogsLogsNotYetAvailable {
            get {
                return ResourceManager.GetString("ConsoleLogsLogsNotYetAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No resource selected.
        /// </summary>
        public static string ConsoleLogsNoResourceSelected {
            get {
                return ResourceManager.GetString("ConsoleLogsNoResourceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} Console Logs.
        /// </summary>
        public static string ConsoleLogsPageTitle {
            get {
                return ResourceManager.GetString("ConsoleLogsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a Resource.
        /// </summary>
        public static string ConsoleLogsSelectAResource {
            get {
                return ResourceManager.GetString("ConsoleLogsSelectAResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown State.
        /// </summary>
        public static string ConsoleLogsUnknownState {
            get {
                return ResourceManager.GetString("ConsoleLogsUnknownState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Watching logs....
        /// </summary>
        public static string ConsoleLogsWatchingLogs {
            get {
                return ResourceManager.GetString("ConsoleLogsWatchingLogs", resourceCulture);
            }
        }
    }
}
