//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Dashboard.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControlsStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlsStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Aspire.Dashboard.Resources.ControlsStrings", typeof(ControlsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ChartContainerUnableToDisplay {
            get {
                return ResourceManager.GetString("ChartContainerUnableToDisplay", resourceCulture);
            }
        }
        
        public static string ChartContainerFiltersHeader {
            get {
                return ResourceManager.GetString("ChartContainerFiltersHeader", resourceCulture);
            }
        }
        
        public static string ChartContainerSelectFilters {
            get {
                return ResourceManager.GetString("ChartContainerSelectFilters", resourceCulture);
            }
        }
        
        public static string ChartContainerGraphTab {
            get {
                return ResourceManager.GetString("ChartContainerGraphTab", resourceCulture);
            }
        }
        
        public static string ChartContainerTableTab {
            get {
                return ResourceManager.GetString("ChartContainerTableTab", resourceCulture);
            }
        }
        
        public static string ChartContainerGraphAccessibleLabel {
            get {
                return ResourceManager.GetString("ChartContainerGraphAccessibleLabel", resourceCulture);
            }
        }
        
        public static string EnvironmentVariablesFilterToggleShowSpecOnly {
            get {
                return ResourceManager.GetString("EnvironmentVariablesFilterToggleShowSpecOnly", resourceCulture);
            }
        }
        
        public static string EnvironmentVariablesFilterToggleShowAll {
            get {
                return ResourceManager.GetString("EnvironmentVariablesFilterToggleShowAll", resourceCulture);
            }
        }
        
        public static string EnvironmentVariablesShowVariableValues {
            get {
                return ResourceManager.GetString("EnvironmentVariablesShowVariableValues", resourceCulture);
            }
        }
        
        public static string EnvironmentVariablesHideVariableValues {
            get {
                return ResourceManager.GetString("EnvironmentVariablesHideVariableValues", resourceCulture);
            }
        }
        
        public static string FilterPlaceholder {
            get {
                return ResourceManager.GetString("FilterPlaceholder", resourceCulture);
            }
        }
        
        public static string GridValueMaskShowValue {
            get {
                return ResourceManager.GetString("GridValueMaskShowValue", resourceCulture);
            }
        }
        
        public static string GridValueMaskHideValue {
            get {
                return ResourceManager.GetString("GridValueMaskHideValue", resourceCulture);
            }
        }
        
        public static string GridValueCopyToClipboard {
            get {
                return ResourceManager.GetString("GridValueCopyToClipboard", resourceCulture);
            }
        }
        
        public static string ExceptionDetailsTitle {
            get {
                return ResourceManager.GetString("ExceptionDetailsTitle", resourceCulture);
            }
        }
        
        public static string GridValueCopied {
            get {
                return ResourceManager.GetString("GridValueCopied", resourceCulture);
            }
        }
        
        public static string PlotlyChartCount {
            get {
                return ResourceManager.GetString("PlotlyChartCount", resourceCulture);
            }
        }
        
        public static string PlotlyChartLength {
            get {
                return ResourceManager.GetString("PlotlyChartLength", resourceCulture);
            }
        }
        
        public static string PlotlyChartValue {
            get {
                return ResourceManager.GetString("PlotlyChartValue", resourceCulture);
            }
        }
        
        public static string NameColumnHeader {
            get {
                return ResourceManager.GetString("NameColumnHeader", resourceCulture);
            }
        }
        
        public static string PropertyGridValueColumnHeader {
            get {
                return ResourceManager.GetString("PropertyGridValueColumnHeader", resourceCulture);
            }
        }
        
        public static string StateColumnHeader {
            get {
                return ResourceManager.GetString("StateColumnHeader", resourceCulture);
            }
        }
        
        public static string SpanDetailsResource {
            get {
                return ResourceManager.GetString("SpanDetailsResource", resourceCulture);
            }
        }
        
        public static string SpanDetailsDuration {
            get {
                return ResourceManager.GetString("SpanDetailsDuration", resourceCulture);
            }
        }
        
        public static string SpanDetailsStartTime {
            get {
                return ResourceManager.GetString("SpanDetailsStartTime", resourceCulture);
            }
        }
        
        public static string ViewLogsLink {
            get {
                return ResourceManager.GetString("ViewLogsLink", resourceCulture);
            }
        }
        
        public static string SummaryDetailsViewSplitHorizontal {
            get {
                return ResourceManager.GetString("SummaryDetailsViewSplitHorizontal", resourceCulture);
            }
        }
        
        public static string SummaryDetailsViewSplitVertical {
            get {
                return ResourceManager.GetString("SummaryDetailsViewSplitVertical", resourceCulture);
            }
        }
        
        public static string SummaryDetailsViewCloseView {
            get {
                return ResourceManager.GetString("SummaryDetailsViewCloseView", resourceCulture);
            }
        }
        
        public static string TotalItemsFooterText {
            get {
                return ResourceManager.GetString("TotalItemsFooterText", resourceCulture);
            }
        }
        
        public static string SelectAnApplication {
            get {
                return ResourceManager.GetString("SelectAnApplication", resourceCulture);
            }
        }
        
        public static string ViewAction {
            get {
                return ResourceManager.GetString("ViewAction", resourceCulture);
            }
        }
        
        public static string LabelAll {
            get {
                return ResourceManager.GetString("LabelAll", resourceCulture);
            }
        }
        
        public static string ChartContainerAllTags {
            get {
                return ResourceManager.GetString("ChartContainerAllTags", resourceCulture);
            }
        }
        
        public static string ChartContainerFilteredTags {
            get {
                return ResourceManager.GetString("ChartContainerFilteredTags", resourceCulture);
            }
        }
        
        public static string ChartContainerOptionsHeader {
            get {
                return ResourceManager.GetString("ChartContainerOptionsHeader", resourceCulture);
            }
        }
        
        public static string ChartContainerShowCountLabel {
            get {
                return ResourceManager.GetString("ChartContainerShowCountLabel", resourceCulture);
            }
        }
        
        public static string LabelNone {
            get {
                return ResourceManager.GetString("LabelNone", resourceCulture);
            }
        }
        
        public static string MetricTableStartColumnHeader {
            get {
                return ResourceManager.GetString("MetricTableStartColumnHeader", resourceCulture);
            }
        }
        
        public static string MetricTableShowLatestValues {
            get {
                return ResourceManager.GetString("MetricTableShowLatestValues", resourceCulture);
            }
        }
        
        public static string MetricTableShowOnlyValueChanges {
            get {
                return ResourceManager.GetString("MetricTableShowOnlyValueChanges", resourceCulture);
            }
        }
        
        public static string MetricTableValueIncreased {
            get {
                return ResourceManager.GetString("MetricTableValueIncreased", resourceCulture);
            }
        }
        
        public static string MetricTableValueDecreased {
            get {
                return ResourceManager.GetString("MetricTableValueDecreased", resourceCulture);
            }
        }
        
        public static string MetricTableValueNoChange {
            get {
                return ResourceManager.GetString("MetricTableValueNoChange", resourceCulture);
            }
        }
        
        public static string MetricTableNoMetricsFound {
            get {
                return ResourceManager.GetString("MetricTableNoMetricsFound", resourceCulture);
            }
        }
        
        public static string ResourceLabel {
            get {
                return ResourceManager.GetString("ResourceLabel", resourceCulture);
            }
        }
        
        public static string TimeOffsetColumnHeader {
            get {
                return ResourceManager.GetString("TimeOffsetColumnHeader", resourceCulture);
            }
        }
        
        public static string EventColumnHeader {
            get {
                return ResourceManager.GetString("EventColumnHeader", resourceCulture);
            }
        }
        
        public static string DurationColumnHeader {
            get {
                return ResourceManager.GetString("DurationColumnHeader", resourceCulture);
            }
        }
        
        public static string TimestampColumnHeader {
            get {
                return ResourceManager.GetString("TimestampColumnHeader", resourceCulture);
            }
        }
        
        public static string DetailsColumnHeader {
            get {
                return ResourceManager.GetString("DetailsColumnHeader", resourceCulture);
            }
        }
        
        public static string ResourceDropdownReplicaAccessibleTitle {
            get {
                return ResourceManager.GetString("ResourceDropdownReplicaAccessibleTitle", resourceCulture);
            }
        }
        
        public static string ApplicationLower {
            get {
                return ResourceManager.GetString("ApplicationLower", resourceCulture);
            }
        }
        
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        public static string StructuredLogsDetailsResource {
            get {
                return ResourceManager.GetString("StructuredLogsDetailsResource", resourceCulture);
            }
        }
        
        public static string StructuredLogsDetailsTimestamp {
            get {
                return ResourceManager.GetString("StructuredLogsDetailsTimestamp", resourceCulture);
            }
        }
        
        public static string ResourceDetailsUrlsHeader {
            get {
                return ResourceManager.GetString("ResourceDetailsUrlsHeader", resourceCulture);
            }
        }
        
        public static string ResourceDetailsEnvironmentVariablesHeader {
            get {
                return ResourceManager.GetString("ResourceDetailsEnvironmentVariablesHeader", resourceCulture);
            }
        }
        
        public static string ResourceDetailsVolumesHeader {
            get {
                return ResourceManager.GetString("ResourceDetailsVolumesHeader", resourceCulture);
            }
        }
        
        public static string ResourceHealthChecksHeader {
            get {
                return ResourceManager.GetString("ResourceHealthChecksHeader", resourceCulture);
            }
        }
        
        public static string ResourceDetailsResourceHeader {
            get {
                return ResourceManager.GetString("ResourceDetailsResourceHeader", resourceCulture);
            }
        }
        
        public static string SpanDetailsEventsHeader {
            get {
                return ResourceManager.GetString("SpanDetailsEventsHeader", resourceCulture);
            }
        }
        
        public static string SpanDetailsResourceHeader {
            get {
                return ResourceManager.GetString("SpanDetailsResourceHeader", resourceCulture);
            }
        }
        
        public static string SpanDetailsSpanHeader {
            get {
                return ResourceManager.GetString("SpanDetailsSpanHeader", resourceCulture);
            }
        }
        
        public static string StructuredLogsDetailsContextHeader {
            get {
                return ResourceManager.GetString("StructuredLogsDetailsContextHeader", resourceCulture);
            }
        }
        
        public static string StructuredLogsDetailsExceptionHeader {
            get {
                return ResourceManager.GetString("StructuredLogsDetailsExceptionHeader", resourceCulture);
            }
        }
        
        public static string StructuredLogsDetailsLogEntryHeader {
            get {
                return ResourceManager.GetString("StructuredLogsDetailsLogEntryHeader", resourceCulture);
            }
        }
        
        public static string StructuredLogsDetailsResourceHeader {
            get {
                return ResourceManager.GetString("StructuredLogsDetailsResourceHeader", resourceCulture);
            }
        }
        
        public static string TraceDetailAttributesHeader {
            get {
                return ResourceManager.GetString("TraceDetailAttributesHeader", resourceCulture);
            }
        }
        
        public static string SpanDetailsContextHeader {
            get {
                return ResourceManager.GetString("SpanDetailsContextHeader", resourceCulture);
            }
        }
        
        public static string MetricTableExemplarsColumnHeader {
            get {
                return ResourceManager.GetString("MetricTableExemplarsColumnHeader", resourceCulture);
            }
        }
        
        public static string MetricTableViewExemplarsLabel {
            get {
                return ResourceManager.GetString("MetricTableViewExemplarsLabel", resourceCulture);
            }
        }
        
        public static string PlotlyChartTime {
            get {
                return ResourceManager.GetString("PlotlyChartTime", resourceCulture);
            }
        }
        
        public static string PlotlyChartExemplars {
            get {
                return ResourceManager.GetString("PlotlyChartExemplars", resourceCulture);
            }
        }
        
        public static string PlotlyChartTrace {
            get {
                return ResourceManager.GetString("PlotlyChartTrace", resourceCulture);
            }
        }
        
        public static string SpanDetailsLinksHeader {
            get {
                return ResourceManager.GetString("SpanDetailsLinksHeader", resourceCulture);
            }
        }
        
        public static string SpanDetailsSpanPrefix {
            get {
                return ResourceManager.GetString("SpanDetailsSpanPrefix", resourceCulture);
            }
        }
        
        public static string SpanDetailsSpanColumnHeader {
            get {
                return ResourceManager.GetString("SpanDetailsSpanColumnHeader", resourceCulture);
            }
        }
        
        public static string SpanDetailsDetailsColumnHeader {
            get {
                return ResourceManager.GetString("SpanDetailsDetailsColumnHeader", resourceCulture);
            }
        }
        
        public static string SpanDetailsBacklinksHeader {
            get {
                return ResourceManager.GetString("SpanDetailsBacklinksHeader", resourceCulture);
            }
        }
        
        public static string PageToolbarLandmark {
            get {
                return ResourceManager.GetString("PageToolbarLandmark", resourceCulture);
            }
        }
        
        public static string FluentDataGridHeaderCellResizeLabel {
            get {
                return ResourceManager.GetString("FluentDataGridHeaderCellResizeLabel", resourceCulture);
            }
        }
        
        public static string FluentDataGridHeaderCellResizeDiscreteLabel {
            get {
                return ResourceManager.GetString("FluentDataGridHeaderCellResizeDiscreteLabel", resourceCulture);
            }
        }
        
        public static string FluentDataGridHeaderCellSortButtonText {
            get {
                return ResourceManager.GetString("FluentDataGridHeaderCellSortButtonText", resourceCulture);
            }
        }
        
        public static string FluentDataGridHeaderCellSortAscendingButtonText {
            get {
                return ResourceManager.GetString("FluentDataGridHeaderCellSortAscendingButtonText", resourceCulture);
            }
        }
        
        public static string FluentDataGridHeaderCellSortDescendingButtonText {
            get {
                return ResourceManager.GetString("FluentDataGridHeaderCellSortDescendingButtonText", resourceCulture);
            }
        }
        
        public static string FluentDataGridHeaderCellResizeButtonText {
            get {
                return ResourceManager.GetString("FluentDataGridHeaderCellResizeButtonText", resourceCulture);
            }
        }
        
        public static string FluentDataGridHeaderCellGrowAriaLabelText {
            get {
                return ResourceManager.GetString("FluentDataGridHeaderCellGrowAriaLabelText", resourceCulture);
            }
        }
        
        public static string FluentDataGridHeaderCellResetAriaLabelText {
            get {
                return ResourceManager.GetString("FluentDataGridHeaderCellResetAriaLabelText", resourceCulture);
            }
        }
        
        public static string FluentDataGridHeaderCellShrinkAriaLabelText {
            get {
                return ResourceManager.GetString("FluentDataGridHeaderCellShrinkAriaLabelText", resourceCulture);
            }
        }
        
        public static string FluentDataGridHeaderCellSubmitAriaLabelText {
            get {
                return ResourceManager.GetString("FluentDataGridHeaderCellSubmitAriaLabelText", resourceCulture);
            }
        }
        
        public static string StructuredFilteringFilters {
            get {
                return ResourceManager.GetString("StructuredFilteringFilters", resourceCulture);
            }
        }
        
        public static string StructuredFilteringNoFilters {
            get {
                return ResourceManager.GetString("StructuredFilteringNoFilters", resourceCulture);
            }
        }
        
        public static string StructuredFilteringAddFilter {
            get {
                return ResourceManager.GetString("StructuredFilteringAddFilter", resourceCulture);
            }
        }
        
        public static string LabelEmpty {
            get {
                return ResourceManager.GetString("LabelEmpty", resourceCulture);
            }
        }
        
        public static string LabelUnset {
            get {
                return ResourceManager.GetString("LabelUnset", resourceCulture);
            }
        }
        
        public static string ActionsColumnHeader {
            get {
                return ResourceManager.GetString("ActionsColumnHeader", resourceCulture);
            }
        }
        
        public static string ActionViewDetailsText {
            get {
                return ResourceManager.GetString("ActionViewDetailsText", resourceCulture);
            }
        }
        
        public static string ActionsButtonText {
            get {
                return ResourceManager.GetString("ActionsButtonText", resourceCulture);
            }
        }
        
        public static string ActionStructuredLogsText {
            get {
                return ResourceManager.GetString("ActionStructuredLogsText", resourceCulture);
            }
        }
        
        public static string ResourceDetailsTypeHeader {
            get {
                return ResourceManager.GetString("ResourceDetailsTypeHeader", resourceCulture);
            }
        }
        
        public static string ResourceDetailsReferences {
            get {
                return ResourceManager.GetString("ResourceDetailsReferences", resourceCulture);
            }
        }
        
        public static string ResourceDetailsBackReferences {
            get {
                return ResourceManager.GetString("ResourceDetailsBackReferences", resourceCulture);
            }
        }
        
        public static string VolumePathColumnHeader {
            get {
                return ResourceManager.GetString("VolumePathColumnHeader", resourceCulture);
            }
        }
        
        public static string VolumeMountTypeColumnHeader {
            get {
                return ResourceManager.GetString("VolumeMountTypeColumnHeader", resourceCulture);
            }
        }
        
        public static string ClearAllResources {
            get {
                return ResourceManager.GetString("ClearAllResources", resourceCulture);
            }
        }
        
        public static string ClearSelectedResource {
            get {
                return ResourceManager.GetString("ClearSelectedResource", resourceCulture);
            }
        }
        
        public static string ClearPendingSelectedResource {
            get {
                return ResourceManager.GetString("ClearPendingSelectedResource", resourceCulture);
            }
        }
        
        public static string ChartContainerOverflowDescription {
            get {
                return ResourceManager.GetString("ChartContainerOverflowDescription", resourceCulture);
            }
        }
        
        public static string ChartContainerOverflowTitle {
            get {
                return ResourceManager.GetString("ChartContainerOverflowTitle", resourceCulture);
            }
        }
        
        public static string ChartContainerOverflowLink {
            get {
                return ResourceManager.GetString("ChartContainerOverflowLink", resourceCulture);
            }
        }
        
        public static string EndpointNameColumnHeader {
            get {
                return ResourceManager.GetString("EndpointNameColumnHeader", resourceCulture);
            }
        }
        
        public static string LinkAddressColumnHeader {
            get {
                return ResourceManager.GetString("LinkAddressColumnHeader", resourceCulture);
            }
        }
        
        public static string ResourceGraphNoEndpoints {
            get {
                return ResourceManager.GetString("ResourceGraphNoEndpoints", resourceCulture);
            }
        }
        
        public static string PauseButtonTitle {
            get {
                return ResourceManager.GetString("PauseButtonTitle", resourceCulture);
            }
        }
        
        public static string ResumeButtonTitle {
            get {
                return ResourceManager.GetString("ResumeButtonTitle", resourceCulture);
            }
        }
        
        public static string ClearSignalsButtonTitle {
            get {
                return ResourceManager.GetString("ClearSignalsButtonTitle", resourceCulture);
            }
        }
        
        public static string TotalItemsFooterCapturePaused {
            get {
                return ResourceManager.GetString("TotalItemsFooterCapturePaused", resourceCulture);
            }
        }
        
        public static string LinkTextColumnHeader {
            get {
                return ResourceManager.GetString("LinkTextColumnHeader", resourceCulture);
            }
        }
        
        public static string ToggleNesting {
            get {
                return ResourceManager.GetString("ToggleNesting", resourceCulture);
            }
        }
        
        public static string ShowHiddenResources {
            get {
                return ResourceManager.GetString("ShowHiddenResources", resourceCulture);
            }
        }
        
        public static string HideHiddenResources {
            get {
                return ResourceManager.GetString("HideHiddenResources", resourceCulture);
            }
        }
    }
}
