//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Dashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControlsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Dashboard.Resources.ControlsStrings", typeof(ControlsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tags.
        /// </summary>
        public static string ChartContainerAllTags {
            get {
                return ResourceManager.GetString("ChartContainerAllTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered tags.
        /// </summary>
        public static string ChartContainerFilteredTags {
            get {
                return ResourceManager.GetString("ChartContainerFilteredTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string ChartContainerFiltersHeader {
            get {
                return ResourceManager.GetString("ChartContainerFiltersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string ChartContainerOptionsHeader {
            get {
                return ResourceManager.GetString("ChartContainerOptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select filters.
        /// </summary>
        public static string ChartContainerSelectFilters {
            get {
                return ResourceManager.GetString("ChartContainerSelectFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show count.
        /// </summary>
        public static string ChartContainerShowCountLabel {
            get {
                return ResourceManager.GetString("ChartContainerShowCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to display chart.
        /// </summary>
        public static string ChartContainerUnableToDisplay {
            get {
                return ResourceManager.GetString("ChartContainerUnableToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DetailsColumnHeader {
            get {
                return ResourceManager.GetString("DetailsColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string DurationColumnHeader {
            get {
                return ResourceManager.GetString("DurationColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        public static string EnvironmentVariablesFilterToggleShowAll {
            get {
                return ResourceManager.GetString("EnvironmentVariablesFilterToggleShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show spec only.
        /// </summary>
        public static string EnvironmentVariablesFilterToggleShowSpecOnly {
            get {
                return ResourceManager.GetString("EnvironmentVariablesFilterToggleShowSpecOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide values.
        /// </summary>
        public static string EnvironmentVariablesHideVariableValues {
            get {
                return ResourceManager.GetString("EnvironmentVariablesHideVariableValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show values.
        /// </summary>
        public static string EnvironmentVariablesShowVariableValues {
            get {
                return ResourceManager.GetString("EnvironmentVariablesShowVariableValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string EventColumnHeader {
            get {
                return ResourceManager.GetString("EventColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter....
        /// </summary>
        public static string FilterPlaceholder {
            get {
                return ResourceManager.GetString("FilterPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string GridValueCopyToClipboard {
            get {
                return ResourceManager.GetString("GridValueCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide value.
        /// </summary>
        public static string GridValueMaskHideValue {
            get {
                return ResourceManager.GetString("GridValueMaskHideValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show value.
        /// </summary>
        public static string GridValueMaskShowValue {
            get {
                return ResourceManager.GetString("GridValueMaskShowValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameColumnHeader {
            get {
                return ResourceManager.GetString("NameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string PlotlyChartCount {
            get {
                return ResourceManager.GetString("PlotlyChartCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string PlotlyChartLength {
            get {
                return ResourceManager.GetString("PlotlyChartLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string PlotlyChartValue {
            get {
                return ResourceManager.GetString("PlotlyChartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string PropertyGridValueColumnHeader {
            get {
                return ResourceManager.GetString("PropertyGridValueColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an application.
        /// </summary>
        public static string SelectAnApplication {
            get {
                return ResourceManager.GetString("SelectAnApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a resource.
        /// </summary>
        public static string SelectAResource {
            get {
                return ResourceManager.GetString("SelectAResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        public static string SpanDetailsDuration {
            get {
                return ResourceManager.GetString("SpanDetailsDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        public static string SpanDetailsService {
            get {
                return ResourceManager.GetString("SpanDetailsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        public static string SpanDetailsStartTime {
            get {
                return ResourceManager.GetString("SpanDetailsStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string SummaryDetailsViewCloseView {
            get {
                return ResourceManager.GetString("SummaryDetailsViewCloseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split horizontal.
        /// </summary>
        public static string SummaryDetailsViewSplitHorizontal {
            get {
                return ResourceManager.GetString("SummaryDetailsViewSplitHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split vertical.
        /// </summary>
        public static string SummaryDetailsViewSplitVertical {
            get {
                return ResourceManager.GetString("SummaryDetailsViewSplitVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time offset.
        /// </summary>
        public static string TimeOffsetColumnHeader {
            get {
                return ResourceManager.GetString("TimeOffsetColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string TimestampColumnHeader {
            get {
                return ResourceManager.GetString("TimestampColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: &lt;strong&gt;{0} results found&lt;/strong&gt;.
        /// </summary>
        public static string TotalItemsFooterText {
            get {
                return ResourceManager.GetString("TotalItemsFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ViewAction {
            get {
                return ResourceManager.GetString("ViewAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View logs.
        /// </summary>
        public static string ViewLogsLink {
            get {
                return ResourceManager.GetString("ViewLogsLink", resourceCulture);
            }
        }
    }
}
