//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Dashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Dashboard.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All.
        /// </summary>
        public static string ResourcesAllTypes {
            get {
                return ResourceManager.GetString("ResourcesAllTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Container.
        /// </summary>
        public static string ResourcesContainerType {
            get {
                return ResourceManager.GetString("ResourcesContainerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Endpoints.
        /// </summary>
        public static string ResourcesEnvironmentVariablesGridEndpointsColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesEnvironmentVariablesGridEndpointsColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Environment.
        /// </summary>
        public static string ResourcesEnvironmentVariablesGridEnvironmentColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesEnvironmentVariablesGridEnvironmentColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name (ID).
        /// </summary>
        public static string ResourcesEnvironmentVariablesGridNameColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesEnvironmentVariablesGridNameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source.
        /// </summary>
        public static string ResourcesEnvironmentVariablesGridSourceColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesEnvironmentVariablesGridSourceColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start Time.
        /// </summary>
        public static string ResourcesEnvironmentVariablesGridStartTimeColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesEnvironmentVariablesGridStartTimeColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à State.
        /// </summary>
        public static string ResourcesEnvironmentVariablesGridStateColumnHeader {
            get {
                return ResourceManager.GetString("ResourcesEnvironmentVariablesGridStateColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Environment Variables for {0}.
        /// </summary>
        public static string ResourcesEnvironmentVariablesHeader {
            get {
                return ResourceManager.GetString("ResourcesEnvironmentVariablesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Executable.
        /// </summary>
        public static string ResourcesExecutableType {
            get {
                return ResourceManager.GetString("ResourcesExecutableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resources.
        /// </summary>
        public static string ResourcesHeader {
            get {
                return ResourceManager.GetString("ResourcesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Environment Variables.
        /// </summary>
        public static string ResourcesNoEnvironmentVariables {
            get {
                return ResourceManager.GetString("ResourcesNoEnvironmentVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No resources found.
        /// </summary>
        public static string ResourcesNoResources {
            get {
                return ResourceManager.GetString("ResourcesNoResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} Resources.
        /// </summary>
        public static string ResourcesPageTitle {
            get {
                return ResourceManager.GetString("ResourcesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Project.
        /// </summary>
        public static string ResourcesProjectType {
            get {
                return ResourceManager.GetString("ResourcesProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resource Types.
        /// </summary>
        public static string ResourcesResourceTypesHeader {
            get {
                return ResourceManager.GetString("ResourcesResourceTypesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type Filter: All Types Visible.
        /// </summary>
        public static string ResourcesTypeFilterAllVisible {
            get {
                return ResourceManager.GetString("ResourcesTypeFilterAllVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type Filter: Filtered.
        /// </summary>
        public static string ResourcesTypeFiltered {
            get {
                return ResourceManager.GetString("ResourcesTypeFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View.
        /// </summary>
        public static string ResourcesViewButtonText {
            get {
                return ResourceManager.GetString("ResourcesViewButtonText", resourceCulture);
            }
        }
    }
}
