//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspire.Dashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StructuredLogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StructuredLogs() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspire.Dashboard.Resources.StructuredLogs", typeof(StructuredLogs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Filter.
        /// </summary>
        public static string StructuredLogsAddFilter {
            get {
                return ResourceManager.GetString("StructuredLogsAddFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All.
        /// </summary>
        public static string StructuredLogsAllTypes {
            get {
                return ResourceManager.GetString("StructuredLogsAllTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Details.
        /// </summary>
        public static string StructuredLogsDetailsColumnTitle {
            get {
                return ResourceManager.GetString("StructuredLogsDetailsColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit Filter.
        /// </summary>
        public static string StructuredLogsEditFilter {
            get {
                return ResourceManager.GetString("StructuredLogsEditFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log Entry Details.
        /// </summary>
        public static string StructuredLogsEntryDetails {
            get {
                return ResourceManager.GetString("StructuredLogsEntryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filters: .
        /// </summary>
        public static string StructuredLogsFilters {
            get {
                return ResourceManager.GetString("StructuredLogsFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Structured Logs.
        /// </summary>
        public static string StructuredLogsHeader {
            get {
                return ResourceManager.GetString("StructuredLogsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Level.
        /// </summary>
        public static string StructuredLogsLevelColumnTitle {
            get {
                return ResourceManager.GetString("StructuredLogsLevelColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message.
        /// </summary>
        public static string StructuredLogsMessageColumnTitle {
            get {
                return ResourceManager.GetString("StructuredLogsMessageColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message filter.
        /// </summary>
        public static string StructuredLogsMessageFilter {
            get {
                return ResourceManager.GetString("StructuredLogsMessageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minimum log level filter.
        /// </summary>
        public static string StructuredLogsMinimumLogFilter {
            get {
                return ResourceManager.GetString("StructuredLogsMinimumLogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Filters.
        /// </summary>
        public static string StructuredLogsNoFilters {
            get {
                return ResourceManager.GetString("StructuredLogsNoFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No structured logs found.
        /// </summary>
        public static string StructuredLogsNoLogsFound {
            get {
                return ResourceManager.GetString("StructuredLogsNoLogsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} Structured Logs.
        /// </summary>
        public static string StructuredLogsPageTitle {
            get {
                return ResourceManager.GetString("StructuredLogsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resource.
        /// </summary>
        public static string StructuredLogsResourceColumnTitle {
            get {
                return ResourceManager.GetString("StructuredLogsResourceColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a Minimum Log Level.
        /// </summary>
        public static string StructuredLogsSelectMinimumLogLevel {
            get {
                return ResourceManager.GetString("StructuredLogsSelectMinimumLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Timestamp.
        /// </summary>
        public static string StructuredLogsTimestampColumnTitle {
            get {
                return ResourceManager.GetString("StructuredLogsTimestampColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trace.
        /// </summary>
        public static string StructuredLogsTraceColumnTitle {
            get {
                return ResourceManager.GetString("StructuredLogsTraceColumnTitle", resourceCulture);
            }
        }
    }
}
