---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "api-deployment"
spec:
  template:
    metadata:
      labels:
        app: "aspire"
        component: "api"
    spec:
      containers:
        - image: "{{ .Values.parameters.api.api_image }}"
          name: "api"
          envFrom:
            - configMapRef:
                name: "api-config"
            - secretRef:
                name: "api-secrets"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: "{{ .Values.parameters.api.port_http }}"
            - name: "https"
              protocol: "TCP"
              containerPort: "{{ .Values.parameters.api.port_https }}"
          imagePullPolicy: "IfNotPresent"
  selector:
    matchLabels:
      app: "aspire"
      component: "api"
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
