---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "sqlserver-statefulset"
spec:
  template:
    metadata:
      labels:
        app: "aspire"
        component: "sqlserver"
    spec:
      containers:
        - image: "mcr.microsoft.com/mssql/server:2022-latest"
          name: "sqlserver"
          envFrom:
            - configMapRef:
                name: "sqlserver-config"
            - secretRef:
                name: "sqlserver-secrets"
          ports:
            - name: "tcp"
              protocol: "TCP"
              containerPort: "1433"
          volumeMounts:
            - name: "sqlserver-data"
              mountPath: "/var/opt/mssql"
          imagePullPolicy: "IfNotPresent"
      volumes:
        - name: "sqlserver-data"
          emptyDir: {}
  selector:
    matchLabels:
      app: "aspire"
      component: "sqlserver"
  replicas: 1
  persistentVolumeClaimRetentionPolicy: {}
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 0
    type: "RollingUpdate"
