//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class KafkaBuilderExtensions
    {
        public static ApplicationModel.IResourceBuilder<KafkaServerResource> AddKafka(this IDistributedApplicationBuilder builder, string name, int? port = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<KafkaServerResource> WithDataBindMount(this ApplicationModel.IResourceBuilder<KafkaServerResource> builder, string source, bool isReadOnly = false) { throw null; }

        public static ApplicationModel.IResourceBuilder<KafkaServerResource> WithDataVolume(this ApplicationModel.IResourceBuilder<KafkaServerResource> builder, string? name = null, bool isReadOnly = false) { throw null; }

        public static ApplicationModel.IResourceBuilder<KafkaUIContainerResource> WithHostPort(this ApplicationModel.IResourceBuilder<KafkaUIContainerResource> builder, int? port) { throw null; }

        public static ApplicationModel.IResourceBuilder<KafkaServerResource> WithKafkaUI(this ApplicationModel.IResourceBuilder<KafkaServerResource> builder, System.Action<ApplicationModel.IResourceBuilder<KafkaUIContainerResource>>? configureContainer = null, string? containerName = null) { throw null; }
    }

    public partial class KafkaServerResource : ApplicationModel.ContainerResource, ApplicationModel.IResourceWithConnectionString, ApplicationModel.IResource, ApplicationModel.IManifestExpressionProvider, ApplicationModel.IValueProvider, ApplicationModel.IValueWithReferences, ApplicationModel.IResourceWithEnvironment
    {
        public KafkaServerResource(string name) : base(default!, default) { }

        public ApplicationModel.ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public ApplicationModel.EndpointReference InternalEndpoint { get { throw null; } }

        public ApplicationModel.EndpointReference PrimaryEndpoint { get { throw null; } }
    }

    public sealed partial class KafkaUIContainerResource : ApplicationModel.ContainerResource
    {
        public KafkaUIContainerResource(string name) : base(default!, default) { }
    }
}