apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-frontend
  labels:
    app: my-frontend
spec:
  selector:
    matchLabels:
      app: my-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: my-frontend
    spec:
      containers:
        - name: main
          image: localhost:5001/my-frontend
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
      terminationGracePeriodSeconds: 180
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

---
apiVersion: v1
kind: Service
metadata:
  name: my-frontend
spec:
  type: LoadBalancer
  selector:
    app: my-frontend
  ports:
  - name: http
    port: 8080
