# Manual trigger pipeline for Azure DevOps tests
# Can be invoked manually with "/azp run azdo-tests"

# Only manual triggers - no automatic builds
trigger: none

# No PR triggers for this pipeline
pr: none

extends:
  template: /eng/pipelines/templates/public-pipeline-template.yml
  parameters:
    # Run integration matrix tests and helix tests for manual runs
    testVariants: '_integration_matrix_tests,_helix_tests'