parameters:
  dbsetup:
    port_http: "8080"
    port_https: "8080"
    dbsetup_image: "dbsetup:latest"
  api:
    port_http: "8080"
    port_https: "8080"
    api_image: "api:latest"
  frontend:
    port_http: "8080"
    port_https: "8080"
    frontend_image: "frontend:latest"
  mycontainer:
    mycontainer_image: "mycontainer:latest"
secrets:
  pg:
    POSTGRES_PASSWORD: ""
  sqlserver:
    MSSQL_SA_PASSWORD: ""
  frontend:
    P1: ""
config:
  pg:
    POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    POSTGRES_USER: "postgres"
  dbsetup:
    ASPNETCORE_URLS: "http://+:$8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  api:
    ASPNETCORE_URLS: "http://+:$8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    ConnectionStrings__azdb: "{azpg.outputs.connectionString};Database=azdb"
  sqlserver:
    ACCEPT_EULA: "Y"
  frontend:
    ASPNETCORE_URLS: "http://+:$8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    P0: ""
    P2: "default"
    P3: ""
