// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0161:Convert to file-scoped namespace", Justification = "Occurs in IgnoresAccessChecksTo.cs, which is generated by the IgnoresAccessChecksToGenerator NuGet package", Scope = "namespaceanddescendants", Target = "System.Runtime.CompilerServices")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "Occurs in IgnoresAccessChecksTo.cs, which is generated by the IgnoresAccessChecksToGenerator NuGet package", Scope = "namespaceanddescendants", Target = "System.Runtime.CompilerServices")]
