apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-service
  labels:
    name: basket-service
spec:
  selector:
    matchLabels:
      name: basket-service
  replicas: 3
  template:
    metadata:
      labels:
        name: basket-service
    spec:
      containers:
        - name: main
          image: localhost:5001/basket-service
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          - containerPort: 8443
          env:
          - name: ConnectionStrings__basketCache
            value: "redis"
          - name: ASPNETCORE_URLS
            value: "https://+:8443;http://+:8080"
          - name: ASPNETCORE_Kestrel__Certificates__Default__Path
            value: "/var/run/secrets/certs/tls.crt"
          - name: ASPNETCORE_Kestrel__Certificates__Default__KeyPath
            value: "/var/run/secrets/certs/tls.key"
          volumeMounts:
          - name: tls
            mountPath: "/var/run/secrets/certs"
            readOnly: true
      volumes:
       - name: tls
         secret:
           secretName: basket-tls
      terminationGracePeriodSeconds: 180
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: basket
spec:
  selector:
    name: basket-service
  clusterIP: None
  ports:
  - name: http
    port: 8080
  - name: https
    port: 8443
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: basket-tls
  namespace: default
spec:
  # Secret names are always required.
  secretName: basket-tls

  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - eShop LLC
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - basket
  # Issuer references are always required.
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
