apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    name: catalog-service
spec:
  selector:
    matchLabels:
      name: catalog-service
  replicas: 3
  template:
    metadata:
      labels:
        name: catalog-service
    spec:
      containers:
        - name: main
          image: localhost:5001/catalog-service
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          #- containerPort: 443
          env:
          - name: ConnectionStrings__CatalogDb
            value: "Host=postgres-service;Database=catalog;Username=postgres;Password=postgres"
      terminationGracePeriodSeconds: 180
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: catalog
spec:
  selector:
    name: catalog-service
  clusterIP: None
  ports:
  - name: http
    port: 8080
  #- name: https
  #  port: 433
