parameters:
  agentOs: 'windows'
  jobNameSuffix: 'windows_x64'
  extraBuildArgs: ''
  codeSign: false

jobs:

- template: /eng/common/templates-official/jobs/jobs.yml@self
  parameters:
    enableMicrobuild: ${{ eq(parameters.codeSign, true) }}
    enableMicrobuildForMacAndLinux: ${{ and(eq(parameters.codeSign, true), ne(parameters.agentOs, 'windows')) }}
    enableTelemetry: true
    # Publish build logs
    enablePublishBuildArtifacts: true

    jobs:
    - job: BuildNative_${{ parameters.jobNameSuffix }}
      displayName: Native ${{ parameters.jobNameSuffix }}
      timeoutInMinutes: 20

      variables:
      - ${{ if eq(parameters.codeSign, true) }}:
        - _buildArgs: '--sign'
      - ${{ else }}:
        - _buildArgs: ''

      - ${{ if eq(parameters.agentOs, 'windows') }}:
        - scriptName: build.cmd
      - ${{ else }}:
        - scriptName: build.sh

      pool:
        ${{ if eq(parameters.agentOs, 'windows') }}:
          - name: NetCore1ESPool-Internal
            image: windows.vs2022preview.amd64
            agentOs: windows
        ${{ if eq(parameters.agentOs, 'linux') }}:
          - name: NetCore1ESPool-Internal
            image: 1es-mariner-2
            agentOs: linux
        ${{ if eq(parameters.agentOs, 'macos') }}:
          - name: Azure Pipelines
            vmImage: macOS-latest-internal
            agentOs: macOS

      preSteps:
        - checkout: self
          fetchDepth: 1
          clean: true

      #steps:
        #- script: >-
            #$(Build.SourcesDirectory)/$(scriptName)
            #--ci
            #--build
            #--restore
            #$(_buildArgs)
            #${{ parameters.extraBuildArgs }}
            #-bl:$(Build.Arcade.LogsPath)Build.binlog
          #displayName: Build native packages

        #- task: 1ES.PublishBuildArtifacts@1
          #displayName: Publish Artifacts
          #condition: always()
          #inputs:
            #PathtoPublish: '$(Build.Arcade.ArtifactsPath)packages/'
            #ArtifactName: native_archives_${{ parameters.jobNameSuffix }}
