//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Microsoft.EntityFrameworkCore.Cosmos
{
    public sealed partial class EntityFrameworkCoreCosmosSettings
    {
        public System.Uri? AccountEndpoint { get { throw null; } set { } }

        public string? ConnectionString { get { throw null; } set { } }

        public Azure.Core.TokenCredential? Credential { get { throw null; } set { } }

        public string? DatabaseName { get { throw null; } set { } }

        public bool DisableTracing { get { throw null; } set { } }

        public string? Region { get { throw null; } set { } }

        public System.TimeSpan? RequestTimeout { get { throw null; } set { } }
    }
}

namespace Microsoft.Extensions.Hosting
{
    public static partial class AspireAzureEFCoreCosmosExtensions
    {
        public static void AddCosmosDbContext<TContext>(this IHostApplicationBuilder builder, string connectionName, System.Action<Aspire.Microsoft.EntityFrameworkCore.Cosmos.EntityFrameworkCoreCosmosSettings>? configureSettings = null, System.Action<EntityFrameworkCore.DbContextOptionsBuilder>? configureDbContextOptions = null)
            where TContext : EntityFrameworkCore.DbContext { }

        public static void AddCosmosDbContext<TContext>(this IHostApplicationBuilder builder, string connectionName, string databaseName, System.Action<Aspire.Microsoft.EntityFrameworkCore.Cosmos.EntityFrameworkCoreCosmosSettings>? configureSettings = null, System.Action<EntityFrameworkCore.DbContextOptionsBuilder>? configureDbContextOptions = null)
            where TContext : EntityFrameworkCore.DbContext { }

        public static void EnrichCosmosDbContext<TContext>(this IHostApplicationBuilder builder, System.Action<Aspire.Microsoft.EntityFrameworkCore.Cosmos.EntityFrameworkCoreCosmosSettings>? configureSettings = null)
            where TContext : EntityFrameworkCore.DbContext { }
    }
}