//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class PythonAppResourceBuilderExtensions
    {
        [System.Obsolete("Use AddPythonScript, AddPythonModule, or AddPythonExecutable and chain with .WithVirtualEnvironment(...).WithArgs(...) instead.")]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public static ApplicationModel.IResourceBuilder<Python.PythonAppResource> AddPythonApp(this IDistributedApplicationBuilder builder, string name, string appDirectory, string scriptPath, string virtualEnvironmentPath, params string[] scriptArgs) { throw null; }

        [System.Obsolete("Use AddPythonScript, AddPythonModule, or AddPythonExecutable and chain with .WithArgs(...) instead.")]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public static ApplicationModel.IResourceBuilder<Python.PythonAppResource> AddPythonApp(this IDistributedApplicationBuilder builder, string name, string appDirectory, string scriptPath, params string[] scriptArgs) { throw null; }

        [System.Obsolete("Use AddPythonScript, AddPythonModule, or AddPythonExecutable instead for more explicit control over how the Python application is executed.")]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public static ApplicationModel.IResourceBuilder<Python.PythonAppResource> AddPythonApp(this IDistributedApplicationBuilder builder, string name, string appDirectory, string scriptPath) { throw null; }

        public static ApplicationModel.IResourceBuilder<Python.PythonAppResource> AddPythonExecutable(this IDistributedApplicationBuilder builder, string name, string appDirectory, string executableName) { throw null; }

        public static ApplicationModel.IResourceBuilder<Python.PythonAppResource> AddPythonModule(this IDistributedApplicationBuilder builder, string name, string appDirectory, string moduleName) { throw null; }

        public static ApplicationModel.IResourceBuilder<Python.PythonAppResource> AddPythonScript(this IDistributedApplicationBuilder builder, string name, string appDirectory, string scriptPath) { throw null; }

        public static ApplicationModel.IResourceBuilder<Python.PythonAppResource> WithEntrypoint(this ApplicationModel.IResourceBuilder<Python.PythonAppResource> builder, Python.EntrypointType entrypointType, string entrypoint) { throw null; }

        public static ApplicationModel.IResourceBuilder<T> WithUvEnvironment<T>(this ApplicationModel.IResourceBuilder<T> builder)
            where T : Python.PythonAppResource { throw null; }

        public static ApplicationModel.IResourceBuilder<Python.PythonAppResource> WithVirtualEnvironment(this ApplicationModel.IResourceBuilder<Python.PythonAppResource> builder, string virtualEnvironmentPath) { throw null; }
    }
}

namespace Aspire.Hosting.Python
{
    public enum EntrypointType
    {
        Executable = 0,
        Script = 1,
        Module = 2
    }

    public partial class PythonAppResource : ApplicationModel.ExecutableResource, IResourceWithServiceDiscovery, ApplicationModel.IResourceWithEndpoints, ApplicationModel.IResource
    {
        public PythonAppResource(string name, string executablePath, string appDirectory) : base(default!, default!, default!) { }
    }
}