name: AI Test Workflow

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write

jobs:
  aitest:
    # Only run when the comment starts with /aitest on a PR
    if: >-
      ${{
        startsWith(github.event.comment.body, '/aitest') &&
        github.event.issue.pull_request
      }}
    runs-on: ubuntu-latest
    env:
      REPO_OWNER: dotnet
      REPO_NAME: aspire
      GH_CLI_VERSION: 2.80.0
      GH_TOKEN: ${{ secrets.GH_USER_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Parse and validate scenario name
        id: parse_scenario
        run: |
          COMMENT_BODY="${{ github.event.comment.body }}"
          echo "Comment body: $COMMENT_BODY"

          # Extract scenario name from comment
          SCENARIO_NAME=$(echo "$COMMENT_BODY" | \
            grep -oP '^/aitest\s+\K[a-z0-9]+(-[a-z0-9]+)*$' | head -1)

          if [ -z "$SCENARIO_NAME" ]; then
            echo "Error: Invalid or missing scenario name"
            echo "Expected format: /aitest scenario-name"
            echo "Scenario name must be lowercase alphanumeric with hyphens"
            exit 1
          fi

          echo "Scenario name: $SCENARIO_NAME"
          echo "scenario_name=$SCENARIO_NAME" >> $GITHUB_OUTPUT

      - name: Check for prompt file
        id: check_prompt
        run: |
          SCENARIO_NAME="${{ steps.parse_scenario.outputs.scenario_name }}"
          PROMPT_FILE="tests/agent-scenarios/${SCENARIO_NAME}/prompt.md"

          if [ ! -f "$PROMPT_FILE" ]; then
            echo "Error: Prompt file not found at $PROMPT_FILE"
            exit 1
          fi

          echo "Found prompt file: $PROMPT_FILE"
          echo "prompt_file=$PROMPT_FILE" >> $GITHUB_OUTPUT

      - name: Read prompt file
        id: read_prompt
        run: |
          PROMPT_FILE="${{ steps.check_prompt.outputs.prompt_file }}"
          PROMPT=$(cat "$PROMPT_FILE")

          echo "Prompt content:"
          echo "$PROMPT"

          # Store prompt in output (escape newlines for GitHub Actions)
          echo "prompt<<EOF" >> $GITHUB_OUTPUT
          echo "$PROMPT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Download and install GitHub CLI
        run: |
          echo "Downloading GitHub CLI v${GH_CLI_VERSION}..."
          DOWNLOAD_URL="https://github.com/cli/cli/releases/download/v${GH_CLI_VERSION}"
          ARCHIVE_NAME="gh_${GH_CLI_VERSION}_linux_amd64.tar.gz"
          curl -fsSL "${DOWNLOAD_URL}/${ARCHIVE_NAME}" -o gh.tar.gz
          tar -xzf gh.tar.gz
          sudo mv "gh_${GH_CLI_VERSION}_linux_amd64/bin/gh" /usr/local/bin/
          rm -rf gh.tar.gz "gh_${GH_CLI_VERSION}_linux_amd64"

          echo "Verifying GitHub CLI installation..."
          gh --version

      - name: Create agent task
        id: create_agent_task
        run: |
          echo "Creating agent task..."
          PROMPT="${{ steps.read_prompt.outputs.prompt }}"

          # Create the agent task and capture the output
          OUTPUT=$(gh agent-task create \
            --repo "${REPO_OWNER}/${REPO_NAME}" \
            --prompt "$PROMPT" \
            2>&1)

          echo "Agent task output:"
          echo "$OUTPUT"

          # Extract the PR URL from the output
          PR_URL=$(echo "$OUTPUT" | \
            grep -oP 'https://github.com/[^/]+/[^/]+/pull/\d+' | head -1)

          if [ -z "$PR_URL" ]; then
            echo "Warning: Could not extract PR URL from output"
            echo "pr_url=" >> $GITHUB_OUTPUT
          else
            echo "Successfully created agent task with PR: $PR_URL"
            echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR with agent task link
        if: steps.create_agent_task.outputs.pr_url != ''
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea  # v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prUrl = '${{ steps.create_agent_task.outputs.pr_url }}';
            const scenarioName = '${{ steps.parse_scenario.outputs.scenario_name }}';
            const comment = `🤖 **AI Agent Task Created**

            Scenario: **${scenarioName}**

            An AI agent has been triggered to create an Aspire
            application. You can track the progress here:

            ${prUrl}`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
