# Workflow to run tests for a given test project

name: Run Tests

on:
  workflow_call:
    inputs:
      testShortName:
        required: true
        type: string
      testProjectPath:
        # relative the repo root
        required: false
        type: string
      testSessionTimeoutMs:
        required: false
        type: string
        default: "600000"
      testHangTimeout:
        required: false
        type: string
        default: "7m"
      extraTestArgs:
        required: false
        type: string

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          include:
            - os: ubuntu-latest
              name: linux
              dotnet_script: ./dotnet.sh
              build_script: ./build.sh
            - os: windows-latest
              name: windows
              dotnet_script: .\dotnet.cmd
              build_script: .\build.cmd
    timeout-minutes: 60
    name: ${{ matrix.name }}
    steps:
      - name: Validate arguments
        shell: pwsh
        run: |
          if ([string]::IsNullOrEmpty("${{ inputs.testShortName }}")) {
            Write-Error "Error: testShortName is required."
            exit 1
          }

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trust HTTPS development certificate (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: ${{ matrix.dotnet_script }} dev-certs https --trust

      #- name: Trust HTTPS development certificate (Windows)
        #if: matrix.os == 'windows-latest'
        #shell: pwsh
        #run: |
          #dotnet dev-certs https --clean

          #New-SelfSignedCertificate -FriendlyName 'ASP.NET Core HTTPS development certificate' -DnsName @('localhost') -Subject 'CN = localhost' -KeyAlgorithm RSA -KeyLength 2048 -HashAlgorithm sha256 -CertStoreLocation 'Cert:\CurrentUser\My' -TextExtension @('2.5.29.37={text}1.3.6.1.5.5.7.3.1','1.3.6.1.4.1.311.84.1.1={hex}02','2.5.29.19={text}') -KeyUsage DigitalSignature,KeyEncipherment
          #dotnet dev-certs https --check --verbose

      - name: Trust HTTPS development certificate (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          # Thanks for @ damianedwards
          #
          # Define the OID of the certificate you want to trust
          $oid = "1.3.6.1.4.1.311.84.1.1"  # Replace with your actual OID

          # Load certificates from the Local User's Personal store (or another relevant store)
          $sourceStore = New-Object System.Security.Cryptography.X509Certificates.X509Store("My", "CurrentUser")
          $sourceStore.Open("ReadOnly")

          # Find the certificate by its OID
          $cert = $sourceStore.Certificates | Where-Object { $_.Extensions.Oid.Value -eq $oid }

          if ($cert) {
              Write-Host "Certificate found. Moving to Trusted Root Certification Authorities..."

              # Open the Trusted Root store
              $rootStore = New-Object System.Security.Cryptography.X509Certificates.X509Store("Root", "CurrentUser")
              $rootStore.Open("ReadWrite")

              # Add the certificate
              $rootStore.Add($cert)
              $rootStore.Close()

              Write-Host "Certificate successfully added to Trusted Root Certification Authorities."
          } else {
              Write-Host "Certificate with OID $oid not found."
          }

          # Close the source store
          $sourceStore.Close()

      #- name: Trust HTTPS development certificate (Windows)
        #if: matrix.os == 'windows-latest'
        #shell: pwsh
        #run: |
          #dotnet dev-certs https --clean

          ## on windows `dotnet dev-certs https shows a dialog, so instead install the certificate with powershell
          ## Generate new certificate.
          #dotnet dev-certs https

          ## Export the new certificate into a file.
          #$pfxPath = "$(Get-Location)\dotnet-dev-cert-https.pfx"
          #dotnet dev-certs https --export-path $pfxPath

          ## Import the certificate to the machine-wide certificate store.
          #Import-Certificate -FilePath $pfxPath -CertStoreLocation Cert:\CurrentUser\My

          ## Clean up.
          #Remove-Item $pfxPath -Force

          ## Validate new certificate. Unfortunately, "dotnet dev-certs https --check --trust" still reports the
          ## certificate as not trusted.
          #dotnet dev-certs https --check --verbose

      - name: Verify Docker is running
        # nested docker containers not supported on windows
        if: matrix.os == 'ubuntu-latest'
        run: docker info

      - name: Build with packages
        if: ${{ contains(inputs.testProjectPath, 'Aspire.Workload.Tests') }}
        env:
          CI: false
        run: ${{ matrix.build_script }} -restore -build -ci -pack -testnobuild /bl

      - name: Install sdk for workload testing
        if: ${{ contains(inputs.testProjectPath, 'Aspire.Workload.Tests') }}
        env:
          CI: false
        run: >
          ${{ matrix.dotnet_script }} build ${{ github.workspace }}/tests/workloads.proj
          /p:SkipPackageCheckForWorkloadTesting=true
          /bl:${{ github.workspace }}/artifacts/log/Debug/InstallSdkForTesting.binlog


      - name: Install Azure Functions Core Tools
        if: matrix.os == 'ubuntu-latest' && (inputs.testShortName == 'Playground' || inputs.testShortName == 'Azure')
        run: |
          sudo apt-get update
          sudo apt-get install -y azure-functions-core-tools-4

      - name: Compute test project path
        id: compute_project_path
        shell: pwsh
        env:
          CI: false
        run: |
          $testShortName = "${{ inputs.testShortName }}"
          $overrideTestProjectPath = "${{ inputs.testProjectPath }}"
          $projectPath1 = "${{ github.workspace }}/tests/$testShortName.Tests/$testShortName.Tests.csproj"
          $projectPath2 = "${{ github.workspace }}/tests/Aspire.$testShortName.Tests/Aspire.$testShortName.Tests.csproj"

          if (-not [string]::IsNullOrEmpty($overrideTestProjectPath)) {
              $projectPath = "${{ github.workspace }}/$overrideTestProjectPath"
          } elseif (Test-Path -Path $projectPath1) {
              $projectPath = $projectPath1
          } elseif (Test-Path -Path $projectPath2) {
              $projectPath = $projectPath2
          } else {
              Write-Error "No matching project path found."
              exit 1
          }

          echo "TEST_PROJECT_PATH=$projectPath" >> $env:GITHUB_ENV

      - name: Build test project
        env:
          CI: false
        run: |
          ${{ matrix.build_script }} -restore -ci -build -projects ${{ env.TEST_PROJECT_PATH }}

      # Workaround for bug in Azure Functions Worker SDK. See https://github.com/Azure/azure-functions-dotnet-worker/issues/2969.
      - name: Rebuild for Azure Functions project
        if: inputs.testShortName == 'Playground'
        env:
          CI: false
        run: |
          ${{ matrix.dotnet_script }} build ${{ github.workspace }}/playground/AzureFunctionsEndToEnd/AzureFunctionsEndToEnd.Functions/AzureFunctionsEndToEnd.Functions.csproj /p:SkipUnstableEmulators=true

      - name: Run tests
        id: run-tests
        env:
          CI: false
          DCP_DIAGNOSTICS_LOG_LEVEL: debug
          DCP_DIAGNOSTICS_LOG_FOLDER: ${{ github.workspace }}/testresults/dcp
        run: >
          ${{ matrix.dotnet_script }} test ${{ env.TEST_PROJECT_PATH }}
          /p:ContinuousIntegrationBuild=true
          -s eng/testing/.runsettings
          -l "console;verbosity=normal"
          -l "trx"
          -l "GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true"
          "--blame"
          --blame-hang-timeout ${{ inputs.testHangTimeout }}
          --blame-crash
          --results-directory testresults
          --no-restore
          --no-build
          ${{ inputs.extraTestArgs }}
          --
          RunConfiguration.CollectSourceInformation=true
          RunConfiguration.TestSessionTimeout=${{ inputs.testSessionTimeoutMs }}

      # Save the result of the previous steps - success or failure
      # in the form of a file result-success/result-failure -{name}.rst
      - name: Store result - success
        if: ${{ success() }}
        run: touch result-success-${{ inputs.testShortName }}.rst
      - name: Store result - failure
        if: ${{ !success() }}
        run: touch result-failed-${{ inputs.testShortName }}.rst

      # Upload that result file to artifact named test-job-result-{name}
      - name: Upload test result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-job-result-${{ inputs.testShortName }}-${{ matrix.os }}
          path: result-*.rst

      - name: Dump docker info
        if: always()
        run: |
          docker container ls --all
          docker container ls --all --format json
          docker volume ls
          docker network ls

      - name: Upload logs, and test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ inputs.testShortName }}-${{ matrix.os }}
          path: |
            **/*.binlog
            testresults/**
