name: Update dotnet-install Scripts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *' # Daily at 06:00 UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  update-scripts:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'dotnet' }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Download dotnet-install.sh
        run: |
          curl -sSL -o src/Aspire.Cli/Resources/dotnet-install.sh https://dot.net/v1/dotnet-install.sh

      - name: Download dotnet-install.ps1
        run: |
          curl -sSL -o src/Aspire.Cli/Resources/dotnet-install.ps1 https://dot.net/v1/dotnet-install.ps1

      - name: Create or update pull request
        uses: dotnet/actions-create-pull-request@e8d799aa1f8b17f324f9513832811b0a62f1e0b1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-dotnet-install-scripts
          base: main
          commit-message: "[Automated] Update dotnet-install scripts"
          labels: |
            area-cli
            area-engineering-systems
          title: "[Automated] Update dotnet-install scripts"
          body: "Auto-generated update of embedded dotnet-install.sh and dotnet-install.ps1 scripts from https://dot.net/v1/."
